stationdict = {'ACND': 'A N Dev Nagar',
               'AHA': 'Abhaipur',
               'AYU': 'Abhayapuri Asam',
               'ABS': 'Abohar',
               'ABR': 'Abu Road',
               'ULD': 'Achalda',
               'AH': 'Achhnera Junction',
               'ADD': 'Adas Road',
               'ADVI': 'Adavali',
               'AAR': 'Adesar',
               'ABZ': 'Adgaon Buzurg',
               'ADTL': 'Adhartal',
               'ADQ': 'Adhikari',
               'ADST': 'Adi Saptagram',
               'ADB': 'Adilabad',
               'ADF': 'Adina',
               'AI': 'Adipur',
               'ADTP': 'Adityapur',
               'AD': 'Adoni',
               'ADRA': 'Adra Junction',
               'ANDI': 'Adrsh Ngr Delhi',
               'ADT': 'Aduturai',
               'AGTL': 'Agartala',
               'AGD': 'Agasod',
               'AWP': 'Aghwanpur',
               'AGMN': 'Agomoni',
               'AGY': 'Agori Khas',
               'AGC': 'Agra Cantt',
               'AGA': 'Agra City',
               'AF': 'Agra Fort',
               'AHLR': 'Ahalyapur',
               'AHD': 'Aherwadi',
               'AHN': 'Ahiran',
               'AHH': 'Ahmadgarh',
               'ANG': 'Ahmadnagar',
               'AMP': 'Ahmadpur Junction',
               'ADI': 'Ahmedabad Junction',
               'ADIJ': 'Ahmedabad Mg',
               'ARW': 'Ahraura Road',
               'ASH': 'Aishbagh',
               'AIT': 'Ait',
               'ATMO': 'Aithal',
               'AJR': 'Ajaibpur',
               'AJK': 'Ajakollu',
               'ANI': 'Ajanti',
               'AIA': 'Ajaraka',
               'AJ': 'Ajgain',
               'AJP': 'Ajjampur',
               'AII': 'Ajmer Junction',
               'AJNI': 'Ajni',
               'AJN': 'Ajnod',
               'AKOR': 'Akalkot Road',
               'AKT': 'Akaltara',
               'AKE': 'Akanapet',
               'AMY': 'Akathumuri',
               'AKJ': 'Akbarganj',
               'AKN': 'Akbarnagar',
               'ABP': 'Akbarpur',
               'AKVD': 'Akividu',
               'API': 'Akkaraippatti',
               'AKD': 'Akodia',
               'AK': 'Akola Junction',
               'AKR': 'Akolner',
               'AKOT': 'Akot',
               'AYRN': 'Akshaywat R Ngr',
               'AKRD': 'Akurdi',
               'ALAI': 'Alai',
               'ALJ': 'Alai',
               'ALM': 'Alamanda',
               'AMG': 'Alamnagar',
               'ALMR': 'Alampur',
               'ALPR': 'Alampur Road',
               'ALN': 'Alandi',
               'ALER': 'Aler',
               'AIG': 'Algawan',
               'ALB': 'Alia Bada',
               'ALJN': 'Aligarh Junction',
               'APD': 'Alipur Duar',
               'APDJ': 'Alipur Duar Junction',
               'ALY': 'Allahabad City',
               'ALD': 'Allahabad Junction',
               'ALLP': 'Alleppey',
               'AXR': 'Alluru Road',
               'LMT': 'Almatti',
               'LWR': 'Alnavar Junction',
               'ALNI': 'Alniya',
               'AUB': 'Aluabari Road',
               'AWY': 'Aluva',
               'ALW': 'Alwal',
               'AWR': 'Alwar',
               'AGZ': 'Amagura',
               'AN': 'Amalner',
               'AML': 'Amalsad',
               'ARD': 'Amarda Road',
               'AGR': 'Amargarh',
               'AGL': 'Amargol',
               'APA': 'Amarpura',
               'AMPR': 'Amarpura Rathan',
               'AXA': 'Amarsar',
               'AMS': 'Amausi',
               'AADR': 'Amb  Andaura',
               'AGB': 'Ambagaon',
               'UMB': 'Ambala Cant Junction',
               'UBC': 'Ambala City',
               'AMPA': 'Ambalapuzha',
               'ABLE': 'Ambale',
               'ABFC': 'Ambari Falakata',
               'ABH': 'Ambarnath',
               'ABSA': 'Ambasa',
               'ASD': 'Ambasamudram',
               'ABI': 'Ambaturai',
               'ABKA': 'Ambika Kalna',
               'AMBR': 'Ambika Rohina',
               'ABKP': 'Ambikapur',
               'ABD': 'Ambli Road',
               'UMN': 'Ambliyasan',
               'AMB': 'Ambodala',
               'AB': 'Ambur',
               'UDR': 'Amdara',
               'AME': 'Amethi',
               'AGN': 'Amgaon',
               'AGI': 'Amguri',
               'AMLA': 'Amla Junction',
               'AAL': 'Amlai',
               'AMX': 'Amlakhurd',
               'AMLI': 'Amli',
               'ANB': 'Ammanabrolu',
               'AMSA': 'Ammasandra',
               'AMQ': 'Ammuguda',
               'AONI': 'Amoni',
               'AMI': 'Amravati',
               'AMC': 'Amritapura',
               'ASR': 'Amritsar Junction',
               'AMRO': 'Amroha',
               'AKP': 'Anakapalle',
               'ANND': 'Anand Junction',
               'ANDN': 'Anand Nagar',
               'ANVR': 'Anand Vihar',
               'ANVT': 'Anand Vihar Trm',
               'ANF': 'Anandapuram',
               'ANSB': 'Anandpur Sahib',
               'ATP': 'Anantapur',
               'ANE': 'Anantarajupet',
               'ANT': 'Anantnag',
               'APT': 'Anaparti',
               'ANR': 'Anara',
               'ANAS': 'Anas',
               'AVN': 'Anavardikhanpet',
               'ACL': 'Ancheli',
               'UDL': 'Andal Junction',
               'ADH': 'Andheri',
               'ADL': 'Andul',
               'AAM': 'Angadippuram',
               'AFK': 'Angamali',
               'AAG': 'Angar',
               'ANGL': 'Angul',
               'ANO': 'Anjani',
               'AJE': 'Anjar',
               'AJI': 'Anjhi Shahabad',
               'ANKX': 'Ank Mmr Direct',
               'ANK': 'Ankai',
               'AKV': 'Ankleshwar Junction',
               'ANKL': 'Ankola',
               'ANH': 'Ankorah Akorha',
               'ANV': 'Annavaram',
               'NGR': 'Annigeri',
               'ANPR': 'Anpara',
               'ATH': 'Antah',
               'ANTU': 'Antu',
               'AUBR': 'Anugraha N Road',
               'APR': 'Anuppur Junction',
               'AUS': 'Anupshahr',
               'AO': 'Aonla',
               'APL': 'Appikatla',
               'APTA': 'Apta',
               'ARA': 'Ara',
               'ARAG': 'Arag',
               'AJJ': 'Arakkonam',
               'ARK': 'Arakku',
               'AAY': 'Aralvaymozhi',
               'ARN': 'Arand',
               'ANMD': 'Arang Mahanadi',
               'ARR': 'Arariya',
               'ARQ': 'Arariya Court',
               'AVRD': 'Aravali Road',
               'AVK': 'Aravankadu',
               'ARPL': 'Arepalli Halt',
               'ARGD': 'Arigada',
               'ALU': 'Ariyalur',
               'AS': 'Arjansar',
               'AJU': 'Arjuni',
               'ARE': 'Arnetha',
               'ARV': 'Arni Road',
               'ARNA': 'Arnia',
               'ASK': 'Arsikere Junction',
               'ANY': 'Arumuganeri',
               'ARCL': 'Arunachal',
               'APK': 'Aruppukkottai',
               'AFR': 'Asafpur',
               'JOB': 'Asalpur Jobner',
               'ASO': 'Asangaon',
               'ASN': 'Asansol Junction',
               'AST': 'Asaoti',
               'ASV': 'Asarva Junction',
               'AQG': 'Ashapura Gomat',
               'ASKN': 'Ashok Nagar',
               'AP': 'Ashokapuram',
               'ASTG': 'Ashtegaon',
               'ASAF': 'Asifabad Road',
               'ANA': 'Aslana',
               'ASL': 'Aslaoda',
               'AT': 'Asnoti',
               'AXK': 'Asokhar',
               'AAS': 'Asranada',
               'AWM': 'Aswapuram',
               'ATT': 'Atari',
               'ATE': 'Atarra',
               'AEL': 'Ateli',
               'ATL': 'Athmal Gola',
               'ARP': 'Atrampur',
               'ATRU': 'Atru',
               'ATS': 'Attabira',
               'ATR': 'Attar',
               'AL': 'Attili',
               'AIP': 'Attippattu',
               'ATU': 'Attur',
               'ATUL': 'Atul',
               'AJRE': 'Aujari',
               'AED': 'Aulenda',
               'AUNG': 'Aung',
               'ARJ': 'Aunrihar Junction',
               'AWB': 'Aurangabad',
               'OSA': 'Ausa Road',
               'AVS': 'Auvaneswsarem',
               'AUWA': 'Auwa',
               'AVD': 'Avadi',
               'ATPA': 'Awantipura',
               'ATNR': 'Awatarnagar',
               'AY': 'Ayodhya',
               'APN': 'Ayodhyapattanam',
               'AMH': 'Azamgarh',
               'AZR': 'Azamnagar Road',
               'ACLE': 'Azimganj City',
               'AZ': 'Azimganj Junction',
               'BEY': 'B Cement Nagar',
               'BTP': 'Babatpur',
               'BV': 'Babhnan',
               'BAB': 'Babina',
               'BBA': 'Babrala',
               'BBO': 'Babugarh',
               'BUPH': 'Babupeth',
               'BCHL': 'Bacheli',
               'BCN': 'Bachhrawan',
               'BCA': 'Bachwara Junction',
               'BAD': 'Bad',
               'BDBA': 'Badabandha',
               'BDM': 'Badami',
               'BPY': 'Badampudi',
               'BPB': 'Badarpur Junction',
               'BDWS': 'Badarwas',
               'BDXX': 'Bade Arapur',
               'BDHL': 'Badhal',
               'BDWA': 'Badhwa Bara',
               'BDZ': 'Badkulla',
               'BHB': 'Badla Ghat',
               'BUD': 'Badlapur',
               'BHD': 'Badli',
               'BUDM': 'Badmal',
               'BDU': 'Badnapur',
               'BD': 'Badnera Junction',
               'BDDR': 'Badodar',
               'BNZ': 'Badshahnagar',
               'BSE': 'Badshahpur',
               'BLPR': 'Badulipar',
               'BPG': 'Badurpur Ghat',
               'BWS': 'Badwasi',
               'BUG': 'Bagaha',
               'BGHI': 'Bagahai Road',
               'BGA': 'Bagalia',
               'BGK': 'Bagalkot',
               'BGBR': 'Bagbahra',
               'BEH': 'Bagdihi',
               'BF': 'Bagetar',
               'BSRX': 'Bagevadi Road',
               'BGH': 'Baghauli',
               'BORA': 'Baghdogra',
               'BGRA': 'Baghnapara',
               'BJQ': 'Baghora',
               'BGPL': 'Baghuapal',
               'BZN': 'Bagnan',
               'BGTA': 'Bagra Tawa',
               'BQN': 'Bagri Nagar',
               'BGX': 'Bagri Sajjanpur',
               'BGMR': 'Bagumra',
               'BAGD': 'Bagwada (Halt)',
               'BWB': 'Bagwali',
               'BSS': 'Bahadur Singh W',
               'BGZ': 'Bahadurgarh',
               'BPD': 'Bahadurpur',
               'BHI': 'Baheri',
               'BJ': 'Bahjoi',
               'BRK': 'Bahraich',
               'BGUA': 'Baiguda',
               'BATL': 'Baihatola',
               'BKTH': 'Baikunth',
               'BRH': 'Baikunthpur Road',
               'BOI': 'Bainchi',
               'BIH': 'Bairagarh',
               'BGU': 'Bairagnia',
               'BALR': 'Baitalpur',
               'BTV': 'Baitarani Road',
               'BYPL': 'Baiyyappanahali',
               'BJG': 'Bajrangarh',
               'BJUD': 'Bajud',
               'BJW': 'Bajva',
               'BQE': 'Bakanian Bhaunr',
               'BQQ': 'Bakhleta',
               'BKP': 'Bakhtiyarpur Junction',
               'BKTL': 'Baktal',
               'BKLE': 'Bakudi',
               'BLRD': 'Bala Road',
               'BBPM': 'Balabhadrapuram',
               'BRAM': 'Balabnramapuram',
               'BGAE': 'Balagarh',
               'BTC': 'Balaghat Junction',
               'BLM': 'Balamu Junction',
               'BABR': 'Balanagar',
               'BLGR': 'Balangir',
               'BLPE': 'Balapalle',
               'BLS': 'Balasore',
               'BLW': 'Balawali',
               'BALE': 'Bale',
               'BLR': 'Balganur',
               'BPQ': 'Balharshah',
               'BAE': 'Baliakheri',
               'BCK': 'Balichak',
               'BVH': 'Ballabgarh',
               'BAHI': 'Ballenahalli',
               'BLLI': 'Balli',
               'BUI': 'Ballia',
               'BLY': 'Bally',
               'BXA': 'Balod',
               'BLT': 'Balotra Junction',
               'BPRH': 'Balpur Halt',
               'BLP': 'Balrampur',
               'BLSD': 'Balsamand',
               'BALU': 'Balugan',
               'BLGT': 'Balurghat',
               'BMNL': 'Bamanwali',
               'BMU': 'Bamhrauli',
               'BMLL': 'Bamla',
               'BMI': 'Bamnia',
               'BMB': 'Bamra',
               'BAMR': 'Bamur',
               'BYN': 'Banahi',
               'BPF': 'Banapura',
               'BNO': 'Banar',
               'BNS': 'Banas',
               'BAND': 'Banaswadi',
               'BVR': 'Banavar',
               'BNSA': 'Banbasa',
               'BNDA': 'Banda Junction',
               'BNU': 'Bandakpur',
               'BDW': 'Bandanwara',
               'BXK': 'Bandarkhal',
               'BDC': 'Bandel Junction',
               'BR': 'Bandh Bareta',
               'BNF': 'Bandhua',
               'BKI': 'Bandikui Junction',
               'BDTS': 'Bandra Terminus',
               'BNC': 'Bangalore Cant',
               'SBC': 'Bangalore Cy Junction',
               'BNCE': 'Bangalore East',
               'BWY': 'Bangarapet',
               'BWT': 'Bangarapet',
               'BGY': 'Bangriposi',
               'BOD': 'Bangrod',
               'BANI': 'Bani',
               'BNBH': 'Bani Bihar',
               'BAHL': 'Banihal',
               'BS': 'Banisar',
               'BAKA': 'Banka',
               'BKG': 'Banka Ghat',
               'BNKR': 'Banka Road Oa',
               'BTK': 'Bankata',
               'BKH': 'Bankhedi',
               'BQA': 'Bankura',
               'BNKI': 'Banmankhi Jn',
               'BAO': 'Banmor',
               'BANO': 'Bano',
               'BPS': 'Banpas',
               'BSAE': 'Bansh Baria',
               'BSBR': 'Banshlai Bridge',
               'BIQ': 'Bansi Paharpur',
               'BSQP': 'Bansipur',
               'BSKO': 'Banskho',
               'BSPX': 'Banspani',
               'BNLW': 'Bansthali Niwai',
               'BGG': 'Banta Rnathgarh',
               'BLL': 'Bantanahal',
               'BNTL': 'Bantawala',
               'BTRA': 'Banthra',
               'BOTI': 'Baori Thikria',
               'BAF': 'Bap',
               'BPP': 'Bapatla',
               'BMKI': 'Bapudm Motihari',
               'MKI': 'Bapudm Motihari',
               'BAR': 'Bar',
               'BJMD': 'Bara Jamda',
               'BRM': 'Barabambo',
               'BBK': 'Barabanki Junction',
               'BBM': 'Barabhum',
               'BBN': 'Barabil',
               'BCQ': 'Barachak',
               'BUA': 'Baradwar',
               'BAGL': 'Baragopal',
               'BHLE': 'Barahat',
               'BRHU': 'Barahu',
               'BRGM': 'Baraigram Jn',
               'BRR': 'Barakar',
               'BARL': 'Baral',
               'BRMT': 'Baramati',
               'BAZ': 'Baran',
               'BRAG': 'Barang',
               'RAA': 'Barara',
               'BJU': 'Barauni Junction',
               'BTU': 'Baraut',
               'BBTR': 'Barbatpur',
               'BCRD': 'Barchi Road',
               'BWN': 'Barddhaman Junction',
               'BRDH': 'Bardhana Halt',
               'BIY': 'Bardoli',
               'BE': 'Bareilly',
               'BRY': 'Bareilly',
               'BC': 'Bareilly City',
               'BJD': 'Barejadi',
               'BQM': 'Barelipur',
               'BRZ': 'Bareta',
               'BET': 'Bareth',
               'BRG': 'Bargarh',
               'BRGA': 'Bargarh Road',
               'BRGW': 'Bargawan',
               'BUQ': 'Bargi',
               'BARH': 'Barh',
               'BRN': 'Barhan',
               'BHW': 'Barharwa Junction',
               'BRYA': 'Barhiya',
               'DKGS': 'Barhiya',
               'BNY': 'Barhni',
               'BBMN': 'Bari Brahman',
               'BUP': 'Bariarpur',
               'BPO': 'Baripada',
               'BRW': 'Bariwala',
               'BRKA': 'Barka Kana',
               'BKA': 'Barkhera',
               'BSYA': 'Barkisalalya',
               'BKJ': 'Barkur',
               'BLAX': 'Barlai',
               'BME': 'Barmer',
               'BNN': 'Barnala',
               'BOF': 'Barog',
               'BRPL': 'Barpali',
               'BXP': 'Barpathar',
               'BPRD': 'Barpeta Road',
               'BP': 'Barrackpore',
               'BJR': 'Barrajpur',
               'BYS': 'Barsali',
               'BTW': 'Barsi Town',
               'BOE': 'Barsoi Junction',
               'BZO': 'Barsola',
               'BBGN': 'Barua Bamungaon',
               'BRUD': 'Barud',
               'BWR': 'Barwa Sagar',
               'BRWD': 'Barwadih Junction',
               'BWW': 'Barwaha',
               'BXC': 'Barwala',
               'BYHA': 'Barya Ram',
               'BZY': 'Basai',
               'BSPL': 'Basampalle',
               'BSTP': 'Basantapur',
               'BSX': 'Basar',
               'BSI': 'Basbari',
               'BTG': 'Basharatganj',
               'BBQ': 'Basin Bridge Junction',
               'BMF': 'Basmat',
               'BANE': 'Basni',
               'BAI': 'Bassi',
               'BSPN': 'Bassi Pathanam',
               'BTS': 'Basta',
               'BST': 'Basti',
               'BSGN': 'Basugaon',
               'BSKH': 'Basukinath',
               'BU': 'Baswa',
               'BAT': 'Batala Junction',
               'BSLE': 'Bataspur',
               'BTIC': 'Bathinda Cantt.',
               'BVA': 'Bauria Junction',
               'BWL': 'Bawal',
               'BWK': 'Bawani Khera',
               'BXN': 'Bayana Junction',
               'BUT': 'Baytu',
               'BVM': 'Bayyavaram',
               'BZLE': 'Bazarsau',
               'BPZ': 'Bazpur',
               'BEAS': 'Beas',
               'BER': 'Beawar',
               'BHWA': 'Bechhiwara',
               'BMT': 'Begampet',
               'BGW': 'Begdewadi',
               'BGS': 'Begu Sarai',
               'BEG': 'Behtagokul',
               'BHLA': 'Behula',
               'BFR': 'Bekal Fort',
               'BELA': 'Bela',
               'BTX': 'Bela Tal',
               'BLK': 'Belakoba',
               'BPA': 'Belampalli',
               'BAP': 'Belapur',
               'BLSR': 'Belasar',
               'BLDA': 'Belda',
               'BEB': 'Beldanga',
               'BIG': 'Belgahna',
               'BGM': 'Belgaum',
               'BLH': 'Belgharia',
               'BYL': 'Belha',
               'BMKD': 'Bellamkonda',
               'BYC': 'Bellary Cant',
               'BAY': 'Bellary Junction',
               'BNHL': 'Bellenahalli',
               'BPH': 'Belpahar',
               'BXM': 'Belrayan',
               'BLSN': 'Belsonda',
               'BLTR': 'Belthara Road',
               'BWD': 'Belvandi',
               'BEHR': 'Beohari',
               'BRNA': 'Berawanya',
               'BCH': 'Berchha',
               'BPC': 'Berhampore Crt',
               'BRMO': 'Bermo',
               'BSRL': 'Besroli',
               'BMH': 'Betamcherla',
               'BEW': 'Betavad',
               'BTPD': 'Bethampurdi',
               'BTY': 'Bethuadahari',
               'BTQ': 'Betnoti',
               'BTH': 'Bettiah',
               'BZU': 'Betul',
               'BNL': 'Bevinahalu',
               'BAH': 'Bhabhar',
               'BFT': 'Bhabta',
               'BBU': 'Bhabua Road',
               'BCO': 'Bhachau',
               'BCOB': 'Bhachau Bg',
               'BDN': 'Bhadan',
               'BUU': 'Bhadanpur',
               'BWH': 'Bhadaura',
               'BVB': 'Bhadbhadaghat',
               'BBAI': 'Bhadbhunja',
               'BDI': 'Bhadli',
               'BOY': 'Bhadohi',
               'BDCR': 'Bhadrachalam Road',
               'BHC': 'Bhadrakh',
               'BDVT': 'Bhadravati',
               'BHR': 'Bhadreshwar',
               'BHDR': 'Bhadri',
               'BBY': 'Bhadroli',
               'VAA': 'Bhaga Junction',
               'ZZZZ': 'Bhagalpur',
               'BGP': 'Bhagalpur',
               'BGKT': 'Bhagat Ki Kothi',
               'BQG': 'Bhagwangola',
               'BNR': 'Bhagwanpur',
               'BGPR': 'Bhagwanpura',
               'BRU': 'Bhairoganj',
               'BOG': 'Bhairongarh',
               'BKPT': 'Bhakarapet',
               'BKNG': 'Bhakti Nagar',
               'BHLK': 'Bhalki',
               'BFM': 'Bhalui',
               'BKRD': 'Bhaluka Road F',
               'BLMR': 'Bhalukmara',
               'BUL': 'Bhalulata',
               'BLMK': 'Bhalumaska',
               'BLNI': 'Bhalwani',
               'BAK': 'Bhan Kari',
               'BNP': 'Bhanapur',
               'BUX': 'Bhandak',
               'BRD': 'Bhandara Road',
               'BHME': 'Bhandaridah',
               'BHU': 'Bhandu Motidau',
               'BHNS': 'Bhansi',
               'BNUD': 'Bhanvad',
               'BNVD': 'Bhanvad',
               'BHTK': 'Bhanwar Tonk',
               'BNWS': 'Bhanwasa',
               'BTKP': 'Bharat Kup',
               'BTE': 'Bharatpur Junction',
               'BHRL': 'Bharoli',
               'BNT': 'Bharthana',
               'BH': 'Bharuch Junction',
               'BSZ': 'Bharwa Sumerpur',
               'BRE': 'Bharwari',
               'BYT': 'Bhatapara',
               'BHTL': 'Bhatel',
               'BTI': 'Bhatinda Junction',
               'BTSD': 'Bhatisuda(Halt)',
               'BHTA': 'Bhatiya',
               'BTKL': 'Bhatkal',
               'BTJL': 'Bhatkal',
               'BTT': 'Bhatni Junction',
               'BHG': 'Bhaton Ki Gali',
               'BHTR': 'Bhatpar Rani',
               'BQU': 'Bhattiprolu',
               'BHT': 'Bhattu',
               'BVP': 'Bhavanagar Para',
               'BVNR': 'Bhavani Nagar',
               'BVC': 'Bhavnagar Trmus',
               'BWM': 'Bhawani Mandi',
               'BWIP': 'Bhawanipatna',
               'BYR': 'Bhayandar',
               'BHY': 'Bhayavadar',
               'BDH': 'Bhedia',
               'BEP': 'Bheerpur',
               'BHJA': 'Bheja',
               'BRGT': 'Bheraghat',
               'BFY': 'Bhesana',
               'BILA': 'Bheslana',
               'BHET': 'Bhestan',
               'BGVN': 'Bhigwan',
               'BKU': 'Bhiknur',
               'BLD': 'Bhilad',
               'BIA': 'Bhilai',
               'BPHB': 'Bhilai Pwr Hs',
               'BQR': 'Bhilainagar',
               'BVQ': 'Bhilavdi',
               'BLDI': 'Bhildi',
               'BHL': 'Bhilwara',
               'BMD': 'Bhimadolu',
               'BIML': 'Bhimal',
               'BMC': 'Bhimalgondi',
               'BMN': 'Bhimana',
               'BMSB': 'Bhimasar Bg',
               'BVRM': 'Bhimavaram Junction',
               'BVRT': 'Bhimavaram Town',
               'BMGA': 'Bhimgara',
               'BMKJ': 'Bhimkhoj',
               'BMRN': 'Bhimrana',
               'BZM': 'Bhimsen',
               'BIX': 'Bhind',
               'BWA': 'Bhinwaliya',
               'BIK': 'Bhira Kheri',
               'BTO': 'Bhitaura',
               'BHTN': 'Bhitoni',
               'BVS': 'Bhivpuri Road',
               'BIRD': 'Bhiwandi Road',
               'BNW': 'Bhiwani',
               'BNWC': 'Bhiwani City',
               'BPRS': 'Bhogpur Sirwal',
               'BPR': 'Bhojipura Junction',
               'BOJ': 'Bhojo',
               'BJE': 'Bhojudih Junction',
               'BOKR': 'Bhokar',
               'BOKE': 'Bhoke',
               'BHV': 'Bhoma',
               'BHNE': 'Bhone',
               'BGQ': 'Bhongaon',
               'BG': 'Bhongir',
               'BON': 'Bh Onra',
               'BPL': 'Bhopal  Junction',
               'BPKA': 'Bhopalka',
               'BFJ': 'Bhoras Budrukh',
               'BRTK': 'Bhortex',
               'BBS': 'Bhubaneswar',
               'BCU': 'Bhuchchu',
               'BPK': 'Bhugaon',
               'BHUJ': 'Bhuj',
               'BHLP': 'Bhulanpur',
               'BLO': 'Bhulon',
               'BSJ': 'Bhupalsagar',
               'BEF': 'Bhupdeopur',
               'VPO': 'Bhupia Mau',
               'BHKD': 'Bhurkunda',
               'BSDP': 'Bhusandpur',
               'BSL': 'Bhusaval Junction',
               'BTSR': 'Bhuteshwar',
               'BN': 'Bibinagar',
               'BIC': 'Bichia',
               'BID': 'Bidadi',
               'BDNP': 'Bidanpur',
               'BIDR': 'Bidar',
               'BNXR': 'Bidhan Nagar',
               'BIU': 'Bidupur',
               'BIGA': 'Bigga',
               'BQP': 'Bighapur',
               'BEHS': 'Bihar Sharif',
               'BHZ': 'Bihara',
               'BEA': 'Bihiya',
               'BTA': 'Bihta',
               'BJNR': 'Bijainagar',
               'BJP': 'Bijapur',
               'BJI': 'Bijauli',
               'VST': 'Bijaysota',
               'BJF': 'Bijni',
               'BJO': 'Bijnor',
               'BIJR': 'Bijoor',
               'BJK': 'Bijora',
               'BJIH': 'Bijuli Halt',
               'BJRI': 'Bijuri',
               'BWSN': 'Bijwasan',
               'BKN': 'Bikaner Junction',
               'BVL': 'Bikkavolu',
               'BKSL': 'Bikram Shila',
               'BMR': 'Bikrampur',
               'BSP': 'Bilaspur Junction',
               'BLOR': 'Bilaspur Road',
               'BLQR': 'Bilaspur Road',
               'BILD': 'Bildi',
               'BLWR': 'Bileshwar',
               'BZG': 'Bilga',
               'BLG': 'Bilhar Ghat',
               'BLU': 'Bilhaur',
               'BIM': 'Bilimora Junction',
               'BXLL': 'Billi',
               'BLPU': 'Bilpur',
               'BWI': 'Bilwai',
               'BINA': 'Bina Junction',
               'VNK': 'Binaiki',
               'BDYK': 'Bindayaka',
               'BKO': 'Bindki Road',
               'BNV': 'Binnaguri',
               'BIR': 'Bir',
               'BDWL': 'Biradhwal',
               'BAMA': 'Birambad',
               'BRMD': 'Biramdih',
               'BMK': 'Birang Khera',
               'BRPT': 'Birapatti',
               'BRBS': 'Birbans',
               'BLNR': 'Birlanagar',
               'BIJ': 'Birnagar',
               'BEO': 'Birohe',
               'BRLY': 'Biroliya',
               'BRS': 'Birsinghpur',
               'RRB': 'Birur Junction',
               'BIWK': 'Bisalwas Kalan',
               'BSM': 'Bisanattam',
               'BRKH': 'Bisapurkalan',
               'BTJ': 'Bishnathganj',
               'VSU': 'Bishnupur',
               'BSPR': 'Bishrampur',
               'BZR': 'Bisra',
               'BMCK': 'Bissamcuttack',
               'BUB': 'Bissau',
               'BGSF': 'Bisugirsharif',
               'BVN': 'Biswan',
               'BTTR': 'Bitragunta',
               'BRRG': 'Biyavra Rajgarh',
               'BOBS': 'Bobas',
               'VBL': 'Bobbili',
               'BHBK': 'Bodhadi Bujrug',
               'BDWD': 'Bodwad',
               'BHLI': 'Bohali',
               'BNE': 'Bohani',
               'BONA': 'Boinda',
               'BOR': 'Boisar',
               'BXJ': 'Bokajan',
               'BKSC': 'Bokaro Stl City',
               'BKRO': 'Bokaro Thermal',
               'BLX': 'Bolai',
               'BMO': 'Bolarum',
               'BOZ': 'Bolarum Bazar',
               'BLND': 'Bolinna Doaba',
               'BHP': 'Bolpur S Niktn',
               'BLSA': 'Bolsa',
               'BOM': 'Bomadra',
               'BQI': 'Bommidi',
               'BKL': 'Bona Kalu',
               'BNDM': 'Bondamunda',
               'BNGN': 'Bongaigaon',
               'BDAG': 'Bonidanga',
               'BOW': 'Borawar',
               'BXY': 'Bordhal',
               'BIO': 'Bordi',
               'BFD': 'Borhat',
               'BRB': 'Boribial',
               'BRND': 'Boridand',
               'BVI': 'Borivali',
               'BOT': 'Boroti',
               'BGHU': 'Borraguhallu',
               'BTL': 'Bortalao',
               'BRVR': 'Borvihir',
               'BTD': 'Botad Junction',
               'XXXX': 'Bpt Station',
               'BMGM': 'Brahmanagudem',
               'BMPL': 'Brahmanpalli',
               'BAM': 'Brahmapur',
               'BRJN': 'Brajrajnagar',
               'BRLA': 'Brayla Chaurasi',
               'BAL': 'Budalur',
               'BEM': 'Budaun',
               'BDY': 'Buddireddippati',
               'BDHY': 'Budhi',
               'BLZ': 'Budhlada',
               'BNI': 'Budni',
               'BDVL': 'Budvel',
               'BSC': 'Bulandshahr',
               'BUDI': 'Bundi',
               'BEK': 'Bundki',
               'BNDP': 'Buniadpur',
               'BRGL': 'Burgula Halt',
               'BAU': 'Burhanpur',
               'BUH': 'Burhar',
               'BUW': 'Burhwal',
               'BURN': 'Burnpur',
               'BTR': 'Butari',
               'BTBR': 'Buti Bori',
               'BXR': 'Buxar',
               'BDRL': 'Byadarahalli',
               'BYD': 'Byadgi',
               'BY': 'Byculla',
               'BYNR': 'Byndoor',
               'KOP': 'C Shahumharaj T',
               'CNO': 'Cancona',
               'CLR': 'Castle Rock',
               'CVB': 'Cavalry Barrcks',
               'CHB': 'Chabua',
               'CBK': 'Chachaura Bngj',
               'CHCR': 'Chacher',
               'CU': 'Chagallu',
               'CBSA': 'Chaibasa',
               'CNPR': 'Chainpur',
               'CW': 'Chainwa',
               'CJW': 'Chajawa',
               'CJL': 'Chajli',
               'CRWL': 'Chak Rakhwal',
               'CKH': 'Chakand',
               'CHBT': 'Chakarbhatha',
               'CPL': 'Chakarlapalli',
               'CKK': 'Chakarpur',
               'CDH': 'Chakdaha',
               'CKDL': 'Chakdayala',
               'CAA': 'Chakia',
               'CHKB': 'Chakki Bank',
               'CKP': 'Chakradharpur',
               'CAJ': 'Chakraj Mal',
               'CKOD': 'Chakrod',
               'CKS': 'Chaksu',
               'CKU': 'Chakulia',
               'CKX': 'Chakur',
               'CKI': 'Chalakudi',
               'CMZ': 'Chalama',
               'CLI': 'Chalgeri',
               'CSN': 'Chalisgaon Junction',
               'CHKE': 'Challakere',
               'CLPE': 'Challavaripalle',
               'CLD': 'Chalsa Junction',
               'CHM': 'Chalthan',
               'CMX': 'Chamagram',
               'CJR': 'Chamaraj',
               'CMNR': 'Chamarajanagar',
               'CMJ': 'Chamarajapuram',
               'CPH': 'Champa',
               'CPN': 'Champaner Road Jn',
               'CPS': 'Chand Siau',
               'CAF': 'Chanda Fort',
               'CGR': 'Chandan Nagar',
               'CTPE': 'Chandanattop',
               'CNBI': 'Chandari',
               'CDMR': 'Chandauli Mjhwr',
               'CH': 'Chandausi Junction',
               'CNL': 'Chandawal',
               'CNA': 'Chanderiya',
               'CNDM': 'Chandi Mandir',
               'CHD': 'Chandia Road',
               'CDG': 'Chandigarh',
               'CNI': 'Chandil Junction',
               'CLDY': 'Chandlodiya',
               'CDLD': 'Chandlodiya',
               'CNK': 'Chandok',
               'CGI': 'Chandragiri',
               'CDGR': 'Chandrakona Road',
               'CNE': 'Chandranathpur',
               'CD': 'Chandrapur',
               'CRP': 'Chandrapura',
               'CDSL': 'Chandresal',
               'CND': 'Chandur',
               'CNDB': 'Chandur Bazar',
               'CHTI': 'Chaneti',
               'CGY': 'Changanaseri',
               'CGLA': 'Changotola',
               'CGS': 'Changsari',
               'CHNN': 'Channani',
               'CPT': 'Channapatna',
               'CX': 'Chanol',
               'CAI': 'Chanpatia',
               'CPK': 'Chaparmukh Junction',
               'CJS': 'Charamula Kusum',
               'SMD': 'Charanmahadevi',
               'CRW': 'Charaud',
               'CBT': 'Charbatia',
               'CRN': 'Charegaon',
               'CGE': 'Charghat Pipari',
               'CRK': 'Charkhera',
               'CKD': 'Charkhi Dadri',
               'CHZ': 'Charlapalli',
               'CHV': 'Charvattur',
               'CHJ': 'Chata',
               'CTR': 'Chatra',
               'CHPT': 'Chatrappatti',
               'CAP': 'Chatrapur',
               'CTS': 'Chattriput',
               'CMU': 'Chau Mahla',
               'CBH': 'Chaube',
               'CHOK': 'Chauk',
               'CHH': 'Chaukhandi',
               'CNH': 'Chaunrah',
               'CUX': 'Chaura',
               'CRKR': 'Chaurakheri',
               'CC': 'Chauri Chaura',
               'CSA': 'Chausa',
               'CROA': 'Chautara',
               'CKB': 'Chauth Ka Brwra',
               'CVJ': 'Chavaj',
               'CHLK': 'Chavalkhede',
               'CHA': 'Chawapall',
               'CEL': 'Chebrol',
               'CEM': 'Cheekateegalplm',
               'CGL': 'Chengalpattu',
               'CNGR': 'Chengannur',
               'MSB': 'Chennai Beach',
               'MAS': 'Chennai Central',
               'MS': 'Chennai Egmore',
               'CSDR': 'Chennasandra',
               'COI': 'Cheoki',
               'CYN': 'Cheriyanad',
               'CQA': 'Cherukara',
               'CTND': 'Chettinad',
               'CAG': 'Chhabra Gugor',
               'CHNR': 'Chhan Arorian',
               'CDRL': 'Chhandrauli',
               'CAER': 'Chhanera',
               'CHP': 'Chhapi',
               'CPR': 'Chhapra',
               'CI': 'Chhapra Kacheri',
               'CE': 'Chharodi',
               'CHRA': 'Chharra',
               'CJN': 'Chhatna',
               'CHN': 'Chhina',
               'CWA': 'Chhindwara Junction',
               'CPDR': 'Chhipadohar',
               'COD': 'Chhota Gudha',
               'COO': 'Chhoti Odai',
               'CLF': 'Chhulha',
               'CCK': 'Chichaki',
               'CDM': 'Chidambaram',
               'CCA': 'Chigicherla',
               'CEU': 'Chiheru',
               'BAW': 'Chik Banavar',
               'CTH': 'Chikalthan',
               'CKHS': 'Chikhli',
               'JRU': 'Chikjajur Junction',
               'CKNI': 'Chikni Road',
               'CKR': 'Chikodi Road',
               'CLU': 'Chilakalapudi',
               'CIL': 'Chilbila Junction',
               'CLDR': 'Chilikidara',
               'CLKA': 'Chilka',
               'CHR': 'Chilkahar',
               'CLO': 'Chilo',
               'CLVR': 'Chiluvur',
               'CMW': 'Chima Pahad',
               'CMDP': 'Chimidipalli',
               'CNC': 'Chinchli',
               'CPD': 'Chinchpada',
               'CCH': 'Chinchvad',
               'CJM': 'Chinna Ganjam',
               'CHSM': 'Chinna Salem',
               'CIV': 'Chinnaravuru',
               'CCI': 'Chinnekuntapali',
               'CPLE': 'Chinpai',
               'CLE': 'Chintalpalli',
               'CNN': 'Chintaman Ganes',
               'CHI': 'Chiplun',
               'CPP': 'Chipurupalle',
               'CLX': 'Chirala',
               'CRWA': 'Chirawa',
               'CRY': 'Chirayinkil',
               'CGN': 'Chirgaon',
               'CHRM': 'Chirmiri',
               'CBN': 'Chit Baragaon',
               'CTHR': 'Chitahra',
               'CIT': 'Chitali',
               'CTF': 'Chitgidda',
               'CTA': 'Chitradurg',
               'CKTD': 'Chitrakot',
               'CTTP': 'Chitrapur (H)',
               'CTT': 'Chitrasani',
               'COE': 'Chitrod',
               'CT': 'Chittapur',
               'CRJ': 'Chittaranjan',
               'COR': 'Chittaurgarh',
               'AAL': 'AMLAI',
               'AAS': 'ASRANADA',
               'ABD': 'AMBLI ROAD',
               'ABKA': 'AMBIKA KALNA',
               'ABLE': 'AMBALE',
               'ABP': 'AKBARPUR',
               'ABR': 'ABU ROAD',
               'ABS': 'ABOHAR',
               'ACL': 'ANCHELI',
               'ACND': 'A N DEV NAGAR',
               'AD': 'ADONI',
               'ADB': 'ADILABAD',
               'ADH': 'ANDHERI',
               'ADI': 'AHMEDABAD JN',
               'ADRA': 'ADRA JN',
               'ADTP': 'ADITYAPUR',
               'AF': 'AGRA FORT',
               'AFK': 'ANGAMALI',
               'AGA': 'AGRA CITY',
               'AGC': 'AGRA CANTT',
               'AGN': 'AMGAON',
               'AH': 'ACHHNERA JN',
               'AHA': 'ABHAIPUR',
               'AHH': 'AHMADGARH',
               'AIG': 'ALGAWAN',
               'AII': 'AJMER JN',
               'AIT': 'AIT',
               'AJI': 'ANJHI SHAHABAD',
               'AJJ': 'ARAKKONAM',
               'AJNI': 'AJNI',
               'AK': 'AKOLA JN',
               'AKD': 'AKODIA',
               'AKE': 'AKANAPET',
               'AKJ': 'AKBARGANJ',
               'AKN': 'AKBARNAGAR',
               'AKOR': 'AKALKOT ROAD',
               'AKP': 'ANAKAPALLE',
               'AKT': 'AKALTARA',
               'AKV': 'ANKLESHWAR JN',
               'AKVD': 'AKIVIDU',
               'AL': 'ATTILI',
               'ALB': 'ALIA BADA',
               'ALD': 'ALLAHABAD JN',
               'ALER': 'ALER',
               'ALJN': 'ALIGARH JN',
               'ALLP': 'ALLEPPEY',
               'ALM': 'ALAMANDA',
               'ALU': 'ARIYALUR',
               'ALY': 'ALLAHABAD CITY',
               'AMB': 'AMBODALA',
               'AME': 'AMETHI',
               'AMG': 'ALAMNAGAR',
               'AMH': 'AZAMGARH',
               'AML': 'AMALSAD',
               'AMLA': 'AMLA JN',
               'AMLI': 'AMLI',
               'AMP': 'AHMADPUR JN',
               'AMPA': 'AMBALAPUZHA',
               'AMRO': 'AMROHA',
               'AN': 'AMALNER',
               'ANB': 'AMMANABROLU',
               'ANDI': 'ADRSH NGR DELHI',
               'ANG': 'AHMADNAGAR',
               'ANGL': 'ANGUL',
               'ANKL': 'ANKOLA',
               'ANND': 'ANAND JN',
               'ANR': 'ANARA',
               'ANV': 'ANNAVARAM',
               'AO': 'AONLA',
               'APDJ': 'ALIPUR DUAR JN',
               'APL': 'APPIKATLA',
               'APR': 'ANUPPUR JN',
               'APT': 'ANAPARTI',
               'ARA': 'ARA',
               'ARJ': 'AUNRIHAR JN',
               'ASK': 'ARSIKERE JN',
               'ASKN': 'ASHOK NAGAR',
               'ASN': 'ASANSOL JN',
               'ASR': 'AMRITSAR JN',
               'ATE': 'ATARRA',
               'ATH': 'ANTAH',
               'ATL': 'ATHMAL GOLA',
               'ATP': 'ANANTAPUR',
               'ATRU': 'ATRU',
               'ATS': 'ATTABIRA',
               'AUB': 'ALUABARI ROAD',
               'AUBR': 'ANUGRAHA N ROAD',
               'AWB': 'AURANGABAD',
               'AWR': 'ALWAR',
               'AWY': 'ALUVA',
               'AY': 'AYODHYA',
               'AZ': 'AZIMGANJ JN',
               'AZR': 'AZAMNAGAR ROAD',
               'BAB': 'BABINA',
               'BALU': 'BALUGAN',
               'BAM': 'BRAHMAPUR',
               'BAP': 'BELAPUR',
               'BAQ': 'GANJ BASODA',
               'BARH': 'BARH',
               'BAU': 'BURHANPUR',
               'BAY': 'BELLARY JN',
               'BBK': 'BARABANKI JN',
               'BBS': 'BHUBANESWAR',
               'BBU': 'BHABUA ROAD',
               'BCH': 'BERCHHA',
               'BCT': 'MUMBAI CENTRAL',
               'BCY': 'VARANASI CITY',
               'BD': 'BADNERA JN',
               'BDC': 'BANDEL JN',
               'BDJ': 'VADAKARA',
               'BDL': 'VINDHYACHAL',
               'BDTS': 'BANDRA TERMINUS',
               'BE': 'BAREILLY',
               'BEA': 'BIHIYA',
               'BEAS': 'BEAS',
               'BER': 'BEAWAR',
               'BFD': 'BORHAT',
               'BGBR': 'BAGBAHRA',
               'BGP': 'BHAGALPUR',
               'BGS': 'BEGU SARAI',
               'BGZ': 'BAHADURGARH',
               'BH': 'BHARUCH JN',
               'BHC': 'BHADRAKH',
               'BHP': 'BOLPUR S NIKTN',
               'BHS': 'VIDISHA',
               'BHTR': 'BHATPAR RANI',
               'BHW': 'BARHARWA JN',
               'BIA': 'BHILAI',
               'BIG': 'BELGAHNA',
               'BIH': 'BAIRAGARH',
               'BIM': 'BILIMORA JN',
               'BINA': 'BINA JN',
               'BJU': 'BARAUNI JN',
               'BKI': 'BANDIKUI JN',
               'BKN': 'BIKANER JN',
               'BKP': 'BAKHTIYARPUR JN',
               'BKSC': 'BOKARO STL CITY',
               'BL': 'VALSAD',
               'BLGR': 'BALANGIR',
               'BLM': 'BALAMU JN',
               'BLS': 'BALASORE',
               'BLTR': 'BELTHARA ROAD',
               'BLZ': 'BUDHLADA',
               'BMB': 'BAMRA',
               'BMT': 'BEGAMPET',
               'BNC': 'BANGALORE CANT',
               'BNCE': 'BANGALORE EAST',
               'BNDM': 'BONDAMUNDA',
               'BNT': 'BHARTHANA',
               'BNZ': 'BADSHAHNAGAR',
               'BOE': 'BARSOI JN',
               'BOR': 'BOISAR',
               'BOY': 'BHADOHI',
               'BPA': 'BELAMPALLI',
               'BPF': 'BANAPURA',
               'BPH': 'BELPAHAR',
               'BPHB': 'BHILAI PWR HS',
               'BPL': 'BHOPAL JN',
               'BPP': 'BAPATLA',
               'BPQ': 'BALHARSHAH',
               'BPRD': 'BARPETA ROAD',
               'BQR': 'BHILAINAGAR',
               'BRC': 'VADODARA JN',
               'BRD': 'BHANDARA ROAD',
               'BRGA': 'BARGARH ROAD',
               'BRJN': 'BRAJRAJNAGAR',
               'BRR': 'BARAKAR',
               'BRS': 'BIRSINGHPUR',
               'BRYA': 'BARHIYA',
               'BSB': 'VARANASI JN',
               'BSL': 'BHUSAVAL JN',
               'BSP': 'BILASPUR JN',
               'BSR': 'VASAI ROAD',
               'BST': 'BASTI',
               'BTA': 'BIHTA',
               'BTE': 'BHARATPUR JN',
               'BTH': 'BETTIAH',
               'BTI': 'BHATINDA JN',
               'BTP': 'BABATPUR',
               'BTT': 'BHATNI JN',
               'BTTR': 'BITRAGUNTA',
               'BUA': 'BARADWAR',
               'BUG': 'BAGAHA',
               'BUH': 'BURHAR',
               'BUI': 'BALLIA',
               'BUP': 'BARIARPUR',
               'BV': 'BABHNAN',
               'BVH': 'BALLABGARH',
               'BVI': 'BORIVALI',
               'BWH': 'BHADAURA',
               'BWM': 'BHAWANI MANDI',
               'BWN': 'BARDDHAMAN JN',
               'BWT': 'BANGARAPET',
               'BXN': 'BAYANA JN',
               'BXR': 'BUXAR',
               'BYL': 'BELHA',
               'BYN': 'BANAHI',
               'BYT': 'BHATAPARA',
               'BZA': 'VIJAYAWADA JN',
               'BZU': 'BETUL',
               'CAA': 'CHAKIA',
               'CAER': 'CHHANERA',
               'CAG': 'CHHABRA GUGOR',
               'CAN': 'KANNUR',
               'CAP': 'CHATRAPUR',
               'CAPE': 'KANYAKUMARI',
               'CAR': 'CHUNAR',
               'CBE': 'COIMBATORE JN',
               'CBF': 'COIMBATORE NRTH',
               'CBK': 'CHACHAURA BNGJ',
               'CBM': 'CUMBUM',
               'CC': 'CHAURI CHAURA',
               'CCA': 'CHIGICHERLA',
               'CCH': 'CHINCHVAD',
               'CCT': 'KAKINADA TOWN',
               'CD': 'CHANDRAPUR',
               'CDG': 'CHANDIGARH',
               'CDGR': 'CHANDRAKONA RD',
               'CDMR': 'CHANDAULI MJHWR',
               'CE': 'CHHARODI',
               'CEL': 'CHEBROL',
               'CGL': 'CHENGALPATTU',
               'CGN': 'CHIRGAON',
               'CGR': 'CHANDAN NAGAR',
               'CGY': 'CHANGANASERI',
               'CH': 'CHANDAUSI JN',
               'CHA': 'CHAWAPALL',
               'CHBT': 'CHAKARBHATHA',
               'CHCR': 'CHACHER',
               'CHD': 'CHANDIA ROAD',
               'CHE': 'SRIKAKULAM ROAD',
               'CHH': 'CHAUKHANDI',
               'CHI': 'CHIPLUN',
               'CHJ': 'CHATA',
               'CHKB': 'CHAKKI BANK',
               'CHL': 'CHOLA',
               'CHM': 'CHALTHAN',
               'CHNN': 'CHANNANI',
               'CHP': 'CHHAPI',
               'CHRM': 'CHIRMIRI',
               'CHV': 'CHARVATTUR',
               'CHZ': 'CHARLAPALLI',
               'CI': 'CHHAPRA KACHERI',
               'CIT': 'CHITALI',
               'CJM': 'CHINNA GANJAM',
               'CJS': 'CHARAMULA KUSUM',
               'CKB': 'CHAUTH KA BRWRA',
               'CKI': 'CHALAKUDI',
               'CKP': 'CHAKRADHARPUR',
               'CKS': 'CHAKSU',
               'CKTD': 'CHITRAKOT',
               'CKU': 'CHAKULIA',
               'CLDY': 'CHANDLODIYA',
               'CLF': 'CHHULHA',
               'CLG': 'KAHALGAON',
               'CLJ': 'COLONELGANJ',
               'CLKA': 'CHILKA',
               'CLR': 'CASTLE ROCK',
               'CLT': 'KOZHIKODE',
               'CLVR': 'CHILUVUR',
               'CLX': 'CHIRALA',
               'CMU': 'CHAU MAHLA',
               'CMZ': 'CHALAMA',
               'CNA': 'CHANDERIYA',
               'CNB': 'KANPUR CENTRAL',
               'CND': 'CHANDUR',
               'CNDM': 'CHANDI MANDIR',
               'CNGR': 'CHENGANNUR',
               'CNH': 'CHAUNRAH',
               'CNI': 'CHANDIL JN',
               'CNK': 'CHANDOK',
               'CNL': 'CHANDAWAL',
               'CNO': 'CANCONA',
               'CNS': 'CHUCHURA',
               'COO': 'CHHOTI ODAI',
               'COR': 'CHITTAURGARH',
               'CPD': 'CHINCHPADA',
               'CPH': 'CHAMPA',
               'CPJ': 'KAPTANGANJ JN',
               'CPK': 'CHAPARMUKH JN',
               'CPL': 'CHAKARLAPALLI',
               'CPN': 'CHAMPANER RD JN',
               'CPP': 'CHIPURUPALLE',
               'CPR': 'CHHAPRA',
               'CPT': 'CHANNAPATNA',
               'CPU': 'CHOPAN',
               'CRJ': 'CHITTARANJAN',
               'CRP': 'CHANDRAPURA',
               'CRR': 'KARAGOLA ROAD',
               'CRY': 'CHIRAYINKIL',
               'CSA': 'CHAUSA',
               'CSN': 'CHALISGAON JN',
               'CSTM': 'MUMBAI CST',
               'CT': 'CHITTAPUR',
               'CTC': 'CUTTACK',
               'CTF': 'CHITGIDDA',
               'CTH': 'CHIKALTHAN',
               'CTO': 'CHITTOOR',
               'CTS': 'CHATTRIPUT',
               'CTT': 'CHITRASANI',
               'CU': 'CHAGALLU',
               'CUK': 'CHURK',
               'CUX': 'CHAURA',
               'CVJ': 'CHAVAJ',
               'CVP': 'KOVILPATTI',
               'CW': 'CHAINWA',
               'CWA': 'CHHINDWARA JN',
               'DAA': 'DATIA',
               'DAB': 'DHARMABAD',
               'DABN': 'DHABAN',
               'DAJ': 'DUROJI',
               'DAKE': 'DAKHINESWAR',
               'DAO': 'DAGHORA',
               'DBA': 'DABRA',
               'DBD': 'DEOBAND',
               'DBEC': 'DEVBALODA CHRDA',
               'DBG': 'DARBHANGA JN',
               'DBR': 'DABHAURA',
               'DBRT': 'DIBRUGARH TOWN',
               'DBU': 'DODBALLAPUR',
               'DD': 'DAUND JN',
               'DDA': 'DURAUNDHA JN',
               'DDE': 'DONDAICHA',
               'DDN': 'DEHRADUN',
               'DDR': 'DADAR',
               'DEC': 'DELHI CANTT',
               'DEE': 'DELHI S ROHILLA',
               'DEL': 'DENDULURU',
               'DEOS': 'DEORIA SADAR',
               'DES': 'DESARI',
               'DG': 'DINDIGUL JN',
               'DGA': 'DIGHWARA',
               'DGG': 'DONGARGARH',
               'DGI': 'DUNGRI',
               'DGO': 'DURGAUTI',
               'DGR': 'DURGAPUR',
               'DHA': 'DHEENA',
               'DHD': 'DAHOD',
               'DHG': 'DHRANGDHRA',
               'DHN': 'DHANBAD JN',
               'DHND': 'DHINDA',
               'DHNE': 'DHONE',
               'DHO': 'DHAULPUR',
               'DIG': 'DUGGIRALA',
               'DIH': 'DHARUADIHI',
               'DIL': 'DILAWARNAGAR',
               'DKD': 'DONAKONDA',
               'DKJ': 'DORNAKAL JN',
               'DKNT': 'DAKANIYA TALAV',
               'DKS': 'DAREKASA',
               'DKZ': 'DELHI KISHANGNJ',
               'DL': 'DALADI',
               'DLI': 'DELHI',
               'DLK': 'DALKOLHA',
               'DLN': 'DILDARNAGAR JN',
               'DLO': 'DALGAON',
               'DLR': 'DULLAHAPUR',
               'DMM': 'DHARMAVARAM JN',
               'DMN': 'DHAMANGAON',
               'DMNJ': 'DAMANJODI',
               'DMO': 'DAMOH',
               'DMT': 'DIGUVAMETTA',
               'DMV': 'DIMAPUR',
               'DNA': 'DEGANA JN',
               'DNK': 'DHANAKYA',
               'DNKL': 'DHENKANAL',
               'DNR': 'DANAPUR',
               'DNV': 'DONKINAVALASA',
               'DO': 'DAUSA',
               'DOA': 'DORAHA',
               'DOE': 'DEORI',
               'DOL': 'DHOLI',
               'DOS': 'DEHRI ON SONE',
               'DPA': 'DURGAPURA',
               'DPJ': 'DHARMAPURI',
               'DPR': 'DHAMPUR',
               'DPU': 'DIPHU',
               'DQG': 'DHUPGURI',
               'DR': 'DADAR',
               'DRD': 'DAHANU ROAD',
               'DRH': 'DHARHARA',
               'DRL': 'DEROL',
               'DRSN': 'DHURWASIN',
               'DRWN': 'DEROWAN P. H.',
               'DSA': 'DELHI SHAHDARA',
               'DSO': 'DESHNOK',
               'DSS': 'DALSINGH SARAI',
               'DTO': 'DALTONGANJ',
               'DTV': 'DHUTRA',
               'DUA': 'DHAURA',
               'DUD': 'DUDHANI',
               'DUI': 'DHURI JN',
               'DURE': 'DUMRAON',
               'DURG': 'DURG',
               'DVD': 'DUVVADA',
               'DVG': 'DAVANGERE',
               'DVL': 'DEVLALI',
               'DWG': 'DEWANGANJ',
               'DWK': 'DWARKA',
               'DWO': 'DOIWALA',
               'DWP': 'DWARAPUDI',
               'DWR': 'DHARWAR',
               'DWX': 'DEWAS',
               'DXG': 'DHARANGAON',
               'DXN': 'DUDDHINAGAR',
               'DYD': 'DARYABAD',
               'DZA': 'DASUYA',
               'ED': 'ERODE JN',
               'EDD': 'EDDULADODDI',
               'EE': 'ELURU',
               'EKC': 'EKCHARI',
               'EKI': 'EKLAKHI',
               'EKM': 'EKAMBARAKUPPAM',
               'EKMA': 'EKMA',
               'EKR': 'EKANGARSARAI',
               'ELM': 'ELIMALA',
               'EN': 'ISAND',
               'ERL': 'ERANIEL',
               'ERN': 'ERNAKULAM TOWN',
               'ERS': 'ERANAKULAM JN',
               'ET': 'ITARSI JN',
               'ETM': 'ETTUMANUR',
               'ETP': 'ETTAPUR ROAD',
               'ETW': 'ETAWAH',
               'EVA': 'EDAVAI',
               'FA': 'FALNA',
               'FAN': 'FATEHNAGAR',
               'FBD': 'FARRUKHABAD',
               'FBG': 'FORBESGANJ',
               'FD': 'FAIZABAD JN',
               'FDB': 'FARIDABAD',
               'FDK': 'FARIDKOT',
               'FDN': 'FARIDABAD NW TN',
               'FGR': 'FATEHGARH',
               'FGSB': 'FATEHGARH SAHIB',
               'FHT': 'FARAH TOWN',
               'FK': 'FEROK',
               'FKG': 'FURKATING JN',
               'FKM': 'FAKIRAGRAM JN',
               'FL': 'PHULERA JN',
               'FLK': 'FALAKATA',
               'FSP': 'FATEH SINGHPURA',
               'FSR': 'FAQARSAR',
               'FTD': 'FATEHABAD CH.JN',
               'FTG': 'FURSATGANJ',
               'FTP': 'FATEHPUR',
               'FTS': 'FATEHPUR SIKRI',
               'FUT': 'FATWA',
               'FYZ': 'FAIZULLAPUR',
               'FZD': 'FIROZABAD',
               'FZL': 'FAZALPUR',
               'FZR': 'FIROZPUR CANT',
               'G': 'GONDIA JN',
               'GA': 'GUDHA',
               'GADJ': 'GANDHINAGAR JPR',
               'GAJ': 'GANESHGANJ',
               'GAM': 'GANJAM',
               'GAP': 'GURPA',
               'GAR': 'GADARWARA',
               'GAYA': 'GAYA JN',
               'GB': 'GAURI BAZAR',
               'GBD': 'GAURIBIDANUR',
               'GCH': 'GACHHIPURA',
               'GCT': 'GHAZIPUR CITY',
               'GD': 'GONDA JN',
               'GDA': 'GODHRA JN',
               'GDB': 'GIDDARBAHA',
               'GDG': 'GADAG JN',
               'GDL': 'GONDAL',
               'GDM': 'GUDMA',
               'GDPT': 'GUDAPARTI',
               'GDR': 'GUDUR JN',
               'GDV': 'GUDIVADA JN',
               'GDYA': 'GHORADONGRI',
               'GGA': 'GHOGA',
               'GGC': 'GANGAPUR CITY',
               'GGD': 'GULLAGUDA',
               'GGJ': 'GOSHAINGANJ',
               'GGN': 'GURGAON',
               'GH': 'GHUGHULI',
               'GHD': 'GARWA ROAD',
               'GHGL': 'GHAGWAL',
               'GHQ': 'GARHWA',
               'GHR': 'GIDHAUR',
               'GHY': 'GUWAHATI',
               'GID': 'GIDDALUR',
               'GIMB': 'GANDHIDHAM BG',
               'GIN': 'GINIGERA',
               'GJ': 'GANGAJHARI',
               'GJD': 'GUJHANDI',
               'GJJ': 'GAJJELAKONDA',
               'GJL': 'GAJRAULA JN',
               'GJUT': 'GANGSAR JAITU',
               'GKH': 'GUSKARA',
               'GKP': 'GORAKHPUR JN',
               'GLG': 'GULABHGANJ',
               'GLP': 'GOLLAPROLU',
               'GLPT': 'GOALPARA TOWN',
               'GMDA': 'GUMADA',
               'GMH': 'GAMHARIA',
               'GMO': 'NSC BOSE J GOMO',
               'GMR': 'GAHMAR',
               'GMS': 'GARHMUKTESAR',
               'GNA': 'GONEANA',
               'GNG': 'GAURIGANJ',
               'GNGD': 'GANGADHARPUR',
               'GNH': 'GANGAKHER',
               'GNP': 'GHANPUR',
               'GNT': 'GUNTUR JN',
               'GNU': 'GANAUR',
               'GNW': 'GANGIWARA',
               'GOGH': 'GOSSAIGAON HAT',
               'GOH': 'GAROT',
               'GOL': 'GOILKERA',
               'GOTN': 'GOTAN',
               'GOY': 'GOVINDPURI',
               'GP': 'RAJ GANGPUR',
               'GPB': 'GHATPRABHA',
               'GPH': 'GARPOS',
               'GPI': 'GAJAPATINAGARAM',
               'GPR': 'GHORPURI',
               'GQL': 'GURLA',
               'GR': 'GULBARGA',
               'GRA': 'GHARAUNDA',
               'GRL': 'GORAUL',
               'GRMR': 'GARHI MANIKPUR',
               'GRRU': 'GURARU',
               'GRY': 'GORAYA',
               'GSP': 'GURDASPUR',
               'GSPR': 'GOSALPUR',
               'GTK': 'GHUTKU',
               'GTL': 'GUNTAKAL JN',
               'GTNR': 'GOMATI NAGAR',
               'GTS': 'GHATSILA',
               'GTW': 'GATORA',
               'GUD': 'GALUDIH',
               'GUNA': 'GUNA',
               'GUR': 'GANAGAPUR ROAD',
               'GVB': 'GUNERU BAMORI',
               'GVD': 'GHOLVAD',
               'GVG': 'GOVINDGARH',
               'GVI': 'GARIVIDI',
               'GVMR': 'GOVINDI MARWAR',
               'GVN': 'GODAVARI',
               'GWD': 'GADWAL',
               'GWL': 'GWALIOR',
               'GWM': 'GANNAVARAM',
               'GY': 'GOOTY',
               'GYM': 'GUDIYATTAM',
               'GYN': 'GYANPUR ROAD',
               'GZB': 'GHAZIABAD',
               'GZH': 'GULZARBAGH',
               'GZL': 'GAZULAPALLI',
               'GZN': 'N GHAZIABAD',
               'HAD': 'HARIPPAD',
               'HAN': 'HINDAUN CITY',
               'HAPA': 'HAPA',
               'HAQ': 'HASTAVARMU',
               'HAR': 'HAMIRPUR ROAD',
               'HAS': 'HASSAN',
               'HAT': 'HATHURAN',
               'HBD': 'HOSHANGABAD',
               'HBG': 'HOWBADH JABLPUR',
               'HBJ': 'HABIBGANJ',
               'HBW': 'HABIBWALA',
               'HCP': 'HARCHANDPUR',
               'HCR': 'HARISCHANDRPUR',
               'HD': 'HARDA',
               'HDA': 'HIRNODA',
               'HDD': 'HADDINAGUNDU',
               'HDE': 'HARDAS BIGHA',
               'HDK': 'HANDIA KHAS',
               'HDN': 'HAIDARNAGAR',
               'HDP': 'HADAPSAR',
               'HDU': 'HARDUA',
               'HDW': 'HALDWANI',
               'HEM': 'HIMAYATNAGAR',
               'HER': 'HER',
               'HFZ': 'HAFIZPETA',
               'HG': 'HOTGI',
               'HGH': 'HAIDERGARH',
               'HGI': 'HAGARI',
               'HGR': 'HEMAGIRI',
               'HGT': 'HINGANGHAT',
               'HHD': 'HUNSIHADGIL',
               'HIL': 'HILSA',
               'HIR': 'HARINAGAR',
               'HJI': 'HOJAI',
               'HJL': 'HEJJALA',
               'HJP': 'HAJIPUR JN',
               'HKG': 'HIRAKUD',
               'HKH': 'HARANYA KHERI',
               'HKL': 'HARKIA KHAL',
               'HKP': 'HAKIMPUR',
               'HLAR': 'HOLE ALUR',
               'HLDD': 'HALDI ROAD',
               'HLDR': 'HALDAUR',
               'HLK': 'HOLALKERE',
               'HLN': 'HOLE NARSIPUR',
               'HLR': 'HALISAHAR',
               'HM': 'HADMATIYA JN',
               'HMG': 'HAMIRGARH',
               'HMH': 'HANUMANGARH JN',
               'HMI': 'HIMMATANA',
               'HML': 'HELEM',
               'HMR': 'HAMIRA',
               'HMT': 'HIMMATNAGAR',
               'HMY': 'HARMUTI',
               'HN': 'HATHBANDH',
               'HNA': 'HONNAVAR',
               'HNS': 'HANSI',
               'HOL': 'HOL',
               'HP': 'HARIPUR',
               'HPP': 'HARPALPUR',
               'HPT': 'HOSPET JN',
               'HPU': 'HAPUR',
               'HQR': 'HIRENANDURU',
               'HR': 'HARPALU',
               'HRB': 'HARRI',
               'HRG': 'HIRDAGARH',
               'HRH': 'HARTHALA',
               'HRI': 'HARDOI',
               'HRNR': 'HIRA NAGAR',
               'HRPG': 'HARPALGANJ',
               'HRR': 'HARIHAR',
               'HRS': 'HATHRAS JN',
               'HRT': 'HARNAUT',
               'HRV': 'HARRAD',
               'HRW': 'HARRAWALA',
               'HSA': 'HASIMARA',
               'HSD': 'HOSDURGA ROAD',
               'HSI': 'HARSAULI',
               'HSK': 'HARISHANKER RD',
               'HSR': 'HISAR',
               'HSRA': 'HOSUR',
               'HSX': 'HOSHIARPUR',
               'HTE': 'HATIA',
               'HTK': 'HATKANAGALE',
               'HTZ': 'HATHIDAH JN',
               'HUP': 'HINDUPUR',
               'HVD': 'HALVAD',
               'HVM': 'HAMSAVARAM',
               'HVR': 'HAVERI',
               'HW': 'HARIDWAR JN',
               'HWH': 'HOWRAH JN',
               'HWT': 'HANWANT',
               'HX': 'CUDDAPAH',
               'HYB': 'HYDERABAD DECAN',
               'HYT': 'HAIAGHAT',
               'HZD': 'HAZARIBAGH RD',
               'HZR': 'HAFIZPUR',
               'IAA': 'INDARA JN',
               'IB': 'IB',
               'IBL': 'INDRABIL',
               'ICL': 'ICHAULI',
               'IDG': 'INDARGARH',
               'IDH': 'IDGAH AGRA JN',
               'IDR': 'INDI ROAD',
               'IGP': 'IGATPURI',
               'IJK': 'IRINJALAKUDA',
               'IKI': 'ITKYALA',
               'IKK': 'IKKAR',
               'IKR': 'IKLEHRA',
               'IMGE': 'ISMAILPUR',
               'IMR': 'IBRAHIMPUR',
               'INDB': 'INDORE JN BG',
               'INDM': 'INDORE JN MG',
               'IPL': 'IDAPLLI',
               'IPM': 'ICHCHPURAM',
               'IPPM': 'IPURUPALEM',
               'IPR': 'ISLAMPUR',
               'IQB': 'IQBALPUR',
               'IQG': 'IQBAL GADH',
               'IRP': 'IRAVIPURAM',
               'ISA': 'ISARDA',
               'ISH': 'ISARWARA',
               'ISM': 'ISMAILA HARYANA',
               'ITA': 'ITOLA',
               'ITR': 'ITWARI',
               'IZN': 'IZZATNAGAR',
               'J': 'JALNA',
               'JAA': 'JHALIDA',
               'JAB': 'YAMUNA BDG AGRA',
               'JAC': 'JALSU',
               'JACN': 'JALSU NANAK',
               'JAIS': 'JAIS',
               'JAJ': 'JHAJHA',
               'JAL': 'JAWALI',
               'JALD': 'JALIYA DEVANI',
               'JAM': 'JAMNAGAR',
               'JAO': 'JAORA',
               'JAQ': 'JANDRAPETA',
               'JAT': 'JAMMU TAWI',
               'JBK': 'JGMBLA KSHNPRM',
               'JBP': 'JABALPUR',
               'JCL': 'JADCHERLA',
               'JDB': 'JAGDALPUR',
               'JDI': 'JHARRADIH',
               'JDL': 'JAGDEVWALA',
               'JDN': 'JAGUDAN',
               'JER': 'JALESWAR',
               'JEUR': 'JEUR',
               'JGM': 'JHARGRAM',
               'JHD': 'JEHANABAD',
               'JHL': 'JAKHAL JN',
               'JHN': 'JAKHIM',
               'JHS': 'JHANSI JN',
               'JHW': 'JHALAWAR ROAD',
               'JID': 'JAGI ROAD',
               'JIND': 'JIND JN',
               'JJK': 'JHINJHAK',
               'JJKR': 'JAJPUR K ROAD',
               'JJR': 'JEJURI',
               'JKA': 'JAKHVADA',
               'JKE': 'JUKEHI',
               'JKN': 'JAKHANIAN',
               'JKO': 'JAKKALACHERUVU',
               'JL': 'JALGAON JN',
               'JLD': 'JARWAL ROAD',
               'JLL': 'JALALGANJ',
               'JLR': 'JETALSAR JN',
               'JLS': 'JALESAR ROAD',
               'JLW': 'JHALWARA',
               'JLY': 'JHILMILI',
               'JM': 'JALAMB JN',
               'JMG': 'JAMGA',
               'JMK': 'JAMUNAMUKH',
               'JMKL': 'JAMUNIA KALAN',
               'JMKT': 'JAMIKUNTA',
               'JMP': 'JAMALPUR JN',
               'JMPT': 'JIMIDIPETA',
               'JMS': 'JAMSAR',
               'JMT': 'JAMTARA',
               'JMU': 'JAMUI',
               'JMV': 'JAMBARA',
               'JNA': 'JULANA',
               'JND': 'JUNAGADH JN',
               'JNH': 'JANGHAI JN',
               'JNL': 'JANDIALA',
               'JNO': 'JUNNOR DEO',
               'JNU': 'JAUNPUR JN',
               'JOA': 'JANWAL',
               'JOB': 'ASALPUR JOBNER',
               'JOC': 'JOYCHANDI PAHAR',
               'JOM': 'JOGI MAGRA',
               'JOP': 'JAUNPUR CITY',
               'JP': 'JAIPUR',
               'JPE': 'JALPAIGURI ROAD',
               'JPH': 'JHANTIPAHARI',
               'JPL': 'JAPLA',
               'JPV': 'JMTRA PARASWARA',
               'JRA': 'JARAIKELA',
               'JRC': 'JALANDHAR CANT',
               'JRK': 'JERUWA KHERA',
               'JRLE': 'JANGIPUR ROAD',
               'JRMG': 'JAIRAMNAGAR',
               'JRS': 'JORAVASAN',
               'JRT': 'JARTI',
               'JSG': 'JHARSUGUDA JN',
               'JSME': 'JASIDIH JN',
               'JSP': 'JAYASINGPUR',
               'JSR': 'JASRA',
               'JSV': 'JARANDESHWAR',
               'JTI': 'JAITHARI',
               'JTJ': 'JOLARPETTAI',
               'JTR': 'JATKANHAR',
               'JTW': 'JAITWAR',
               'JU': 'JODHPUR JN',
               'JUC': 'JALANDHAR CITY',
               'JUD': 'JAGADHRI',
               'JUDW': 'JAGADHRI WSHOP',
               'JUL': 'JHULASAN',
               'JUR': 'JUTTURU',
               'JVN': 'JORAWARNAGAR JN',
               'JWB': 'JAWAI BANDH',
               'JWL': 'JAJIWAL',
               'JWO': 'JAWAD ROAD',
               'JWP': 'JWALAPUR',
               'JYG': 'JAYNAGAR',
               'JYP': 'JEYPORE',
               'KAH': 'KALHAR',
               'KAN': 'KHANA JN',
               'KAPG': 'KALUPARA GHAT',
               'KAT': 'KHATAULI',
               'KATL': 'KATOL',
               'KBJ': 'KANTABANJI',
               'KCC': 'KRISHNA CANAL',
               'KCG': 'KACHEGUDA',
               'KDG': 'KEDGAON',
               'KDM': 'KESAMUDRAM',
               'KDP': 'KONDAPURAM',
               'KEI': 'KASHI',
               'KGB': 'KARGI ROAD',
               'KGG': 'KHAGARIA JN',
               'KGP': 'KHARAGPUR JN',
               'KGQ': 'KASARAGOD',
               'KHS': 'KHARSIA',
               'KHT': 'SRI KALAHASTI',
               'KIM': 'KIM',
               'KIR': 'KATIHAR JN',
               'KIT': 'KHALLIKOT',
               'KIUL': 'KIUL JN',
               'KJM': 'KRISHNARAJAPURM',
               'KJT': 'KARJAT',
               'KKDE': 'KURUKSHETRA JN',
               'KKLR': 'KAIKOLUR',
               'KKN': 'KHIRKIYA',
               'KKP': 'KOT KAPURA',
               'KLD': 'KHALILABAD',
               'KMBL': 'KHAMBHALIYA',
               'KMI': 'KUMHARI',
               'KMME': 'KUMARDUBI',
               'KMNC': 'KUCHAMAN CITY',
               'KMT': 'KHAMMAM',
               'KMZ': 'KATNI MURWARA',
               'KNE': 'KISHANGANJ',
               'KNN': 'KHANNA',
               'KNT': 'KANTH',
               'KNW': 'KHANDWA',
               'KOJ': 'KOKRAJHAR',
               'KOO': 'KHUSROPUR',
               'KOP': 'C SHAHUMHARAJ T',
               'KOTA': 'KOTA JN',
               'KOU': 'KODURU',
               'KP': 'KAMPTEE',
               'KPD': 'KATPADI JN',
               'KPG': 'KOPARGAON',
               'KPN': 'KUPPAM',
               'KPP': 'KALAPIPAL',
               'KPQ': 'KANNAPURAM',
               'KPV': 'KASHIPUR',
               'KQN': 'KODAIKANAL ROAD',
               'KQR': 'KODERMA',
               'KRAR': 'KHARIAR ROAD',
               'KRBP': 'KHUDIRAM B PUSA',
               'KRD': 'KARAD',
               'KRE': 'KARTARPUR',
               'KRH': 'KHAIRTHAL',
               'KRJ': 'KHURJA JN',
               'KRNT': 'KURNOOL TOWN',
               'KRR': 'KARUR',
               'KS': 'KHETA SARAI',
               'KSB': 'KOSAMBA JN',
               'KSF': 'KHALISPUR',
               'KSG': 'KISHANGARH',
               'KSNG': 'KESINGA',
               'KSRA': 'KASARA',
               'KSV': 'KOSI KALAN',
               'KTE': 'KATNI',
               'KTH': 'KATRASGARH',
               'KTHU': 'KATHUA',
               'KTQ': 'KUDRA',
               'KTU': 'KUTTIPPURAM',
               'KTV': 'KOTTAVALASA',
               'KTYM': 'KOTTAYAM',
               'KUE': 'KURSELA',
               'KUH': 'KHACHROD',
               'KUN': 'KARNAL',
               'KUR': 'KHURDA ROAD JN',
               'KVR': 'KOVVUR',
               'KVU': 'KADAKAVUR',
               'KVZ': 'KAVALI',
               'KWV': 'KURDUVADI',
               'KY': 'KARELI',
               'KYE': 'KHURAI',
               'KYJ': 'KAYANKULAM JN',
               'KYM': 'KADIYAN',
               'KYN': 'KALYAN JN',
               'KYQ': 'KAMAKHYA',
               'KZE': 'KANHANGAD',
               'KZJ': 'KAZIPET JN',
               'LAE': 'LAKHOLI',
               'LAR': 'LALITPUR',
               'LAV': 'LABHA',
               'LBA': 'LAMBHUA',
               'LBG': 'LIMBGAON',
               'LBN': 'LABAN',
               'LC': 'LUCKNOW CITY',
               'LCAE': 'LALBAGH CRT RD',
               'LD': 'LONDA JN',
               'LDA': 'LIDHORA KHURD',
               'LDE': 'LOKDHIKHERA',
               'LDH': 'LUDHIANA JN',
               'LDP': 'LODIPUR BISHNPR',
               'LDR': 'LANDAURA',
               'LDX': 'LADDA',
               'LEDO': 'LEDO',
               'LFG': 'LOWER HAFLONG',
               'LGDH': 'LALAGUDA GATE',
               'LGH': 'LALGARH JN',
               'LGL': 'LALGOLA',
               'LGO': 'LALGOPALGANJ',
               'LGT': 'LANGTING',
               'LHA': 'LEHRA GAGA',
               'LHB': 'LAHABON',
               'LHLL': 'LAHLI',
               'LHN': 'LACHYAN',
               'LHU': 'LOHARU',
               'LIG': 'LINGA',
               'LJN': 'LUCKNOW NE',
               'LJR': 'LANJIGARH ROAD',
               'LKA': 'LANKA',
               'LKBL': 'LAKHABAWAL',
               'LKD': 'LAKODARA',
               'LKDU': 'LANKALAKODERU',
               'LKE': 'LAKHERI',
               'LKKD': 'LAKKADKOT',
               'LKMN': 'LOKMANYA NAGAR',
               'LKMR': 'LAXMIPUR ROAD',
               'LKN': 'LAKHMINIA',
               'LKNA': 'LAKHNA',
               'LKO': 'LUCKNOW NR',
               'LKR': 'LUCKEESARAI JN',
               'LKS': 'LUNKARANSAR',
               'LKT': 'HULKOTI',
               'LKU': 'LAL KUAN',
               'LKY': 'LAKHMAPUR',
               'LLGM': 'LELIGUMA',
               'LLI': 'LALGUDI',
               'LLJ': 'LALGANJ',
               'LLPR': 'LALIT LAKSHMIPR',
               'LM': 'LIMBDI',
               'LMC': 'LAKHAMANCHI',
               'LMD': 'LINGANENIDODDI',
               'LMG': 'LUMDING JN',
               'LMK': 'LIMKHEDA',
               'LMN': 'LACHHMANPUR',
               'LMNR': 'LAKSHMIBAI NGR',
               'LMP': 'LAKHIMPUR',
               'LNA': 'LAMANA',
               'LNK': 'LOHIAN KHAS JN',
               'LNL': 'LONAVALA',
               'LNN': 'LONAND',
               'LNR': 'LUNI RICHHA',
               'LNT': 'LINGTI',
               'LOA': 'LORHA',
               'LONI': 'LONI',
               'LOV': 'LOVEDALE',
               'LPH': 'LOTAPAHAR',
               'LPI': 'LINGAMPALLI',
               'LPJ': 'LALPUR JAM',
               'LPR': 'LILAPUR ROAD',
               'LRD': 'LAR ROAD',
               'LRJ': 'LAKSAR JN',
               'LRU': 'LALPUR UMRI',
               'LS': 'LASALGAON',
               'LSD': 'LUSADIYA',
               'LSE': 'LASERI',
               'LSI': 'LAHERIA SARAI',
               'LSR': 'LASUR',
               'LSX': 'LOISINGHA',
               'LTA': 'LAMTA',
               'LTD': 'LATHIDAD',
               'LTHR': 'LATEHAR',
               'LTR': 'LAKHTAR',
               'LTRR': 'LATUR ROAD',
               'LTT': 'LOKMANYATILAK T',
               'LTV': 'LOTARVA',
               'LUNI': 'LUNI JN',
               'LUR': 'LATUR',
               'LUSA': 'LUSA',
               'LWR': 'ALNAVAR JN',
               'LXA': 'LAKSWA',
               'LXR': 'LUNSERIYA',
               'MABA': 'MANDI BAMORA',
               'MABD': 'MAHBUBABAD',
               'MAG': 'MANGALAGIRI',
               'MAI': 'MEHSI',
               'MAJN': 'MANGALORE JN',
               'MALM': 'MANTHRALAYAM RD',
               'MAN': 'MANINAGAR',
               'MAO': 'MADGAON',
               'MAQ': 'MANGALORE CNTL',
               'MAS': 'CHENNAI CENTRAL',
               'MAU': 'MAU JN',
               'MAUR': 'MAUR',
               'MB': 'MORADABAD',
               'MBD': 'MUSTABADA',
               'MBNR': 'MAHBUBNAGAR',
               'MBY': 'MANDI DABWALI',
               'MCA': 'MECHEDA',
               'MCI': 'MANCHIRYAL',
               'MDDP': 'MANDI DIP',
               'MDN': 'MIDNAPORE',
               'MDNR': 'MODINAGAR',
               'MDP': 'MADHUPUR JN',
               'MDR': 'MADHIRA',
               'MDU': 'MADURAI JN',
               'MEJ': 'MANIYACHCHI JN',
               'MEP': 'MAHIDPUR ROAD',
               'MET': 'MALERKOTLA',
               'MEX': 'MUKERIAN',
               'MFKA': 'MUSAFIR KHANA',
               'MFP': 'MUZAFFARPUR JN',
               'MGN': 'MEGHNAGAR',
               'MGS': 'MUGHAL SARAI JN',
               'MHD': 'MHMDVD KHEDA RD',
               'MHJ': 'MAHAJAN',
               'MID': 'MADHI',
               'MJ': 'MARWAR JN',
               'MJA': 'MEJA ROAD',
               'MJRI': 'MAJRI JN',
               'MKA': 'MOKAMEH JN',
               'MKB': 'MANKATHA',
               'MKC': 'MAKSI',
               'MKI': 'BAPUDM MOTIHARI',
               'MKN': 'MAKRANA JN',
               'MKP': 'MANIKPUR JN',
               'MKR': 'MADDIKERA',
               'MKU': 'MALKAPUR',
               'MKX': 'MORAK',
               'MLD': 'MALIHABAD',
               'MLDT': 'MALDA TOWN',
               'MLMR': 'MELMARUVATTUR',
               'MLPR': 'MALIPUR',
               'MMA': 'MUHAMMADABAD',
               'MML': 'MADAN MAHAL',
               'MMR': 'MANMAD JN',
               'MMV': 'MAHALI MARUP',
               'MNE': 'MANSI JN',
               'MNF': 'MANDA ROAD',
               'MNGD': 'MUNIGUDA',
               'MNI': 'MANGAON',
               'MNP': 'MANANPUR',
               'MNV': 'MUNGAOLI',
               'MOF': 'MONDH',
               'MOO': 'MUDDANURU',
               'MOR': 'MOR',
               'MOT': 'MALOUT',
               'MOU': 'MANOHARPUR',
               'MOZ': 'MUZAFFARNAGAR',
               'MPU': 'MEDAPADU',
               'MRA': 'MORENA',
               'MRBL': 'MURIBAHAL',
               'MRGA': 'MIRYALAGUDA',
               'MRJ': 'MIRAJ JN',
               'MRK': 'MARKAPUR ROAD',
               'MRL': 'MAROLI',
               'MRR': 'MURARAI',
               'MS': 'CHENNAI EGMORE',
               'MSH': 'MAHESANA JN',
               'MSMD': 'MAHASAMUND',
               'MSR': 'MASUR',
               'MSW': 'MASKANWA',
               'MSZ': 'MANSA',
               'MTC': 'MEERUT CITY',
               'MTD': 'MERTA ROAD JN',
               'MTJ': 'MATHURA JN',
               'MTY': 'MULTAI',
               'MUE': 'MUDKHED',
               'MUR': 'MANKAPUR JN',
               'MURI': 'MURI',
               'MUT': 'MEERUT CANT',
               'MUW': 'MATHURAPUR',
               'MVLK': 'MAVELIKARA',
               'MVO': 'MANWATH ROAD',
               'MW': 'MAIRWA',
               'MXH': 'MAKHU',
               'MXN': 'MARIANI JN',
               'MYA': 'MANDYA',
               'MYG': 'MIYAGAM KARJAN',
               'MYR': 'MAIHAR',
               'MYS': 'MYSORE JN',
               'MZP': 'MIRZAPUR',
               'MZR': 'MURTAJAPUR',
               'NAC': 'NAWA CITY',
               'NAD': 'NAGDA JN',
               'NANA': 'NANA',
               'NAT': 'NATHNAGAR',
               'NAW': 'NAWANDGI',
               'NAZJ': 'NAZIRGANJ',
               'NB': 'NIMBHORA',
               'NBA': 'NABHA',
               'NBD': 'NAJIBABAD JN',
               'NBH': 'NIMBAHERA',
               'NBL': 'NIMBAL',
               'NBM': 'NAVABPALEM',
               'NBQ': 'NEW BONGAIGAON',
               'NBR': 'NAMBURU',
               'NCB': 'NEW COOCH BEHAR',
               'NCJ': 'NAGERCOIL JN',
               'ND': 'NADIAD JN',
               'NDAE': 'NABADWIP DHAM',
               'NDB': 'NANDURBAR',
               'NDD': 'NIDADAVOLU JN',
               'NDKD': 'NADIKODE',
               'NDL': 'NANDYAL',
               'NDLS': 'NEW DELHI',
               'NDO': 'NIDUBROLU',
               'NDPU': 'NUDURUPADU',
               'NDZ': 'NIDIGALLU',
               'NED': 'H SAHIB NANDED',
               'NEP': 'NENPUR',
               'NFK': 'NEW FARAKKA JN',
               'NGG': 'NAGINA',
               'NGN': 'NANDGAON',
               'NGNT': 'NEW GUNTUR',
               'NGO': 'NAGAUR',
               'NGP': 'NAGPUR',
               'NGR': 'ANNIGERI',
               'NH': 'NAIHATI JN',
               'NHH': 'NIHALGARH',
               'NHK': 'NAHARKATIYA',
               'NHT': 'NALHATI JN',
               'NIA': 'NAILA',
               'NILE': 'NIMTITA',
               'NIQ': 'NIGAURA',
               'NIRA': 'NIRA',
               'NIU': 'NABIPUR',
               'NJP': 'NEW JALPAIGURI',
               'NK': 'NASIK ROAD',
               'NKD': 'NEKONDA',
               'NKDO': 'NAKKANADODDI',
               'NKE': 'NARKATIAGANJ JN',
               'NKM': 'NAMKON',
               'NKP': 'NIRAKARPUR',
               'NLDA': 'NALGONDA',
               'NLE': 'NILESHWAR',
               'NLI': 'NAMLI',
               'NLKR': 'NILOKHERI',
               'NLPD': 'NALLAPADU',
               'NLR': 'NELLORE',
               'NLV': 'NALBARI',
               'NMH': 'NIMACH',
               'NMZ': 'NEW MAL JN',
               'NN': 'NANDURA',
               'NNA': 'NAUGACHIA',
               'NNN': 'NANGUNERI',
               'NNO': 'NANGLOI',
               'NOI': 'NARIAOLI',
               'NOK': 'NOKHA',
               'NOL': 'NIYOL',
               'NOQ': 'NEW ALIPURDAUR',
               'NPD': 'NAWAPARA ROAD',
               'NPI': 'NIPANIA',
               'NPL': 'NAGALAPALLE',
               'NPNR': 'NEPANAGAR',
               'NR': 'NIPHAD',
               'NRE': 'NANDALUR',
               'NRGR': 'NARANJIPUR',
               'NRKR': 'NARKHER',
               'NRLR': 'NORLA ROAD',
               'NRP': 'NARSIPATNAM RD',
               'NRPD': 'NARAYANPET ROAD',
               'NRT': 'NARASARAOPET',
               'NRW': 'NARWANA JN',
               'NRZB': 'NOWROZABAD',
               'NSL': 'NAGARSOL',
               'NTSK': 'NEW TINSUKIA JN',
               'NU': 'NARSINGHPUR',
               'NUQ': 'NAGAR UNTARI',
               'NUR': 'NARELA',
               'NVG': 'NAWAGAON',
               'NVS': 'NAVSARI',
               'NW': 'NALWAR',
               'NWP': 'NAUPADA JN',
               'NWU': 'NAVAPUR',
               'NXN': 'NUAGAON',
               'NYK': 'NAYA KHARADIA',
               'NYN': 'NAINI',
               'NYO': 'NAYAGAON',
               'NYP': 'NAYADUPETA',
               'NYY': 'NEYYATTINKARA',
               'NZB': 'NIZAMABAD',
               'NZD': 'NUZVID',
               'NZM': 'H NIZAMUDDIN',
               'OBR': 'OBRA DAM',
               'OBVP': 'OBULAVARIPALLI',
               'ODG': 'OBAIDULLA GANJ',
               'ODM': 'ONDAGRAM',
               'OEA': 'ODELA',
               'OGL': 'ONGOLE',
               'OKA': 'OKHLA',
               'OKD': 'OKHA MADHI',
               'OKHA': 'OKHA',
               'OM': 'OMKARESHWAR RD',
               'OML': 'OMALUR',
               'OMLF': 'OLD MALDA',
               'ON': 'UNNAO JN',
               'OPL': 'UPPAL',
               'ORAI': 'ORAI',
               'ORGA': 'ORGA',
               'ORH': 'ODDARAHALLI',
               'ORR': 'ORR',
               'OSN': 'OSIYAN',
               'OTP': 'OTTAPPALAM',
               'OYR': 'WARIA',
               'PAD': 'PARDI',
               'PAK': 'PAKALA JN',
               'PAN': 'PANAGARH',
               'PAO': 'PANOLI',
               'PAP': 'PITHAPURAM',
               'PAR': 'PANDHURNA',
               'PAU': 'PURNA JN',
               'PAVP': 'PEDDA AVUTAPALE',
               'PAY': 'PAYYANUR',
               'PAZ': 'PAYANGADI',
               'PB': 'PUNTAMBA',
               'PBD': 'PEDABRAMADVAM',
               'PBH': 'PARTAPGARH JN',
               'PBN': 'PARBHANI JN',
               'PBR': 'PORBANDAR',
               'PC': 'PACHORA JN',
               'PCLI': 'PALACHAURI',
               'PDH': 'PADADHARI',
               'PDL': 'PENDEKALLU',
               'PDPL': 'PEDDAPALLI',
               'PDRD': 'PINDRA ROAD',
               'PDT': 'PENDURTI',
               'PDU': 'PONDURU',
               'PER': 'PERAMBUR',
               'PFM': 'PHAPHAMAU JN',
               'PGI': 'PARPANANGADI',
               'PGK': 'PILI BANGAN',
               'PGR': 'PUGALUR',
               'PGRL': 'PIDUGURALLA',
               'PGT': 'PALAKKAD',
               'PGU': 'PADUGUPADU',
               'PGW': 'PHAGWARA JN',
               'PHA': 'PATHARIA',
               'PHD': 'PHAPHUND',
               'PHK': 'PUNARAKH',
               'PHN': 'POKHRAYAN',
               'PHR': 'PHILLAUR JN',
               'PIA': 'PIPRAIGAON',
               'PKD': 'PENUKONDA',
               'PKL': 'PAPINAYAKNAHALI',
               'PKR': 'PAKUR',
               'PKU': 'PANSKURA',
               'PKW': 'PILKHUA',
               'PLG': 'PALGHAR',
               'PLJ': 'PALEJ',
               'PLO': 'PULGAON JN',
               'PLP': 'PHULPUR',
               'PLU': 'PATAKOTTACHERU',
               'PMR': 'PITAMBARPUR',
               'PMY': 'PALI MARWAR',
               'PNBE': 'PATNA JN',
               'PNC': 'PATNA SAHEB',
               'PND': 'PENDRA ROAD',
               'PNE': 'PRANTIK',
               'PNK': 'PANKI',
               'PNM': 'PANYAM',
               'PNME': 'PARASNATH',
               'PNP': 'PANIPAT JN',
               'PNPL': 'PANPALI',
               'PNU': 'PALANPUR JN',
               'PNVL': 'PANVEL',
               'PNW': 'PUNDHAG',
               'PNYA': 'PANIAHWA',
               'PPC': 'PIPRAICH',
               'PPD': 'PIPLOD JN',
               'PPI': 'PIPARIYA',
               'PPM': 'PHIRANGIPURAM',
               'PPO': 'PANPOSH',
               'PPR': 'PIPAR ROAD JN',
               'PPT': 'PIRPAINTI',
               'PQN': 'PWN KLAKNDER RD',
               'PRCA': 'PERECHERLA',
               'PRF': 'PARSIPUR',
               'PRG': 'PRAYAG',
               'PRH': 'POWERPET',
               'PRLI': 'PARLI VAIJNATH',
               'PRP': 'PAHARPUR',
               'PRR': 'PURULIA JN',
               'PSA': 'PALASA',
               'PSB': 'PARSABAD',
               'PSDA': 'PASIVEDALA',
               'PST': 'POSOTIA',
               'PTA': 'PATIALA',
               'PTB': 'PATTAMBI',
               'PTJ': 'PODANUR JN',
               'PTK': 'PATHANKOT',
               'PTRU': 'PATRATU',
               'PTU': 'PARTUR',
               'PUA': 'PULLA',
               'PUNE': 'PUNE JN',
               'PURI': 'PURI',
               'PUX': 'PARASIA',
               'PVD': 'PEDDAVADIAPUDI',
               'PVP': 'PARVATIPURAM',
               'PVPT': 'PARVATIPURAM TN',
               'PVU': 'PARAVUR',
               'PWL': 'PALWAL',
               'PWS': 'PHULWARI SHARIF',
               'QLD': 'QUILANDI',
               'QLN': 'KOLLAM JN',
               'R': 'RAIPUR JN',
               'RA': 'RAMPARDA',
               'RAG': 'RAIGIR',
               'RAIR': 'RAIRAKHOL',
               'RANI': 'RANI',
               'RAY': 'RAY',
               'RBA': 'RAMBHA',
               'RBD': 'RAHIMABAD',
               'RBG': 'RAYBAG',
               'RBGJ': 'ROBERTS GANJ',
               'RBL': 'RAE BARELI JN',
               'RBS': 'RUPBAS',
               'RC': 'RAICHUR',
               'RDL': 'RUDAULI',
               'RDM': 'RAMGUNDAM',
               'RDUM': 'RAMPUR DUMRA',
               'RE': 'REWARI',
               'REG': 'REGUPALEM',
               'REI': 'RITHI',
               'REN': 'REN',
               'REWA': 'REWA',
               'RFJ': 'RAFIGANJ',
               'RGD': 'RAJGIR',
               'RGDA': 'RAYAGADA',
               'RGH': 'RAMGARHWA',
               'RGL': 'RENGALI',
               'RGM': 'RANGAPURAM',
               'RGO': 'ROTEGAON',
               'RGP': 'RAGHUNATHPALLI',
               'RGS': 'RINGAS JN',
               'RHE': 'RAKHA MINES',
               'RHG': 'RAJGARH',
               'RIG': 'RAIGARH',
               'RJG': 'RAJGRAM',
               'RJN': 'RAJ NANDGAON',
               'RJP': 'RAZAMPETA',
               'RJPB': 'RJNDR NGR BIHAR',
               'RJS': 'RAJIYASAR',
               'RJT': 'RAJKOT JN',
               'RJY': 'RAJAMUNDRY',
               'RK': 'ROORKEE',
               'RKB': 'RAIKA BAGH',
               'RKD': 'RUKADI',
               'RKM': 'RAJA KI MANDI',
               'RKSN': 'RAJKHARSAWAN JN',
               'RLO': 'RAYALCHERUVU',
               'RMA': 'RAMGANJ MANDI',
               'RMC': 'RAM CHAURA ROAD',
               'RMGM': 'RAMANAGARAM',
               'RMH': 'RANGMAHAL',
               'RMP': 'RAHIMATPUR',
               'RMT': 'RAMGARH CANT',
               'RMU': 'RAMPUR',
               'RN': 'RATNAGIRI',
               'RNBT': 'RAHENBATA',
               'RNC': 'RANCHI',
               'RNE': 'RANJANI',
               'RNG': 'RANIGANJ',
               'RNJD': 'RANJANGAON RD',
               'RNN': 'RAJANKUNTI',
               'RNO': 'RANOLI',
               'RNPR': 'RUPNARAYANPUR',
               'RNQ': 'RENUKUT',
               'RNR': 'RANIBENNUR',
               'RNT': 'RANTHAMBHORE',
               'RNY': 'RANGIYA JN',
               'ROB': 'ROBERTSON',
               'ROHA': 'ROHA',
               'ROK': 'ROHTAK JN',
               'ROP': 'RUPSA JN',
               'ROU': 'ROURKELA',
               'ROZA': 'ROZA JN',
               'RPD': 'RUPAUND',
               'RPH': 'RAMPUR HAT',
               'RPJ': 'RAJPURA JN',
               'RPR': 'RAGHUNATHPUR',
               'RPRD': 'RUPRA ROAD',
               'RPUR': 'RATANPUR',
               'RPZ': 'RANAPRATAPNAGAR',
               'RRB': 'BIRUR JN',
               'RRI': 'RAHURI',
               'RRJ': 'RAMARAJU PALLI',
               'RRL': 'REWRAL',
               'RSR': 'RASRA',
               'RTA': 'RUTHIYAI',
               'RTI': 'RAOTI',
               'RTM': 'RATLAM JN',
               'RU': 'RENIGUNTA JN',
               'RUB': 'RASULABAD',
               'RUL': 'RAULI',
               'RUPC': 'RUDRAPUR CITY',
               'RUR': 'RANPUR',
               'RURA': 'RURA',
               'RV': 'RAVER',
               'RVD': 'RAVIKAMPADU',
               'RWJ': 'RAWANIA DUNGAR',
               'RWL': 'RAIWALA',
               'RWO': 'RANAVAV',
               'RXL': 'RAXAUL JN',
               'RYS': 'RASURIYA',
               'SA': 'SALEM JN',
               'SAN': 'SANDILA',
               'SAW': 'SURIAWAN',
               'SBB': 'SAHIBABAD',
               'SBC': 'BANGALORE CY JN',
               'SBG': 'SAHIBGANJ JN',
               'SBI': 'SABARMATI JN',
               'SBO': 'SABAUR',
               'SBP': 'SAMBALPUR',
               'SBPD': 'SAMBALPUR ROAD',
               'SBPY': 'SAMBALPUR CITY',
               'SBZ': 'SISWA BAZAR',
               'SC': 'SECUNDERABAD JN',
               'SCI': 'SANCHI',
               'SCM': 'SIMHACHALAM',
               'SDAH': 'SEALDAH',
               'SDB': 'SHAHABAD',
               'SDL': 'SHAHDOL',
               'SEB': 'SON NAGAR',
               'SEE': 'SONPUR JN',
               'SEG': 'SHEGAON',
               'SEGM': 'SEVAGRAM',
               'SEH': 'SEHORE',
               'SEO': 'SEOHARA',
               'SGG': 'SULTANGANJ',
               'SGL': 'SAGAULI JN',
               'SGNR': 'SHRI GANGANAGAR',
               'SGO': 'SAUGOR',
               'SGP': 'SOHAGPUR',
               'SGRA': 'SANGARIA',
               'SGZ': 'SHAMGARH',
               'SHDM': 'SHAHBAD MARKNDA',
               'SHE': 'SEORAPHULI',
               'SHG': 'SHAHGANJ JN',
               'SHM': 'SHALIMAR',
               'SHR': 'SIHORA ROAD',
               'SID': 'SIDDHPUR',
               'SIL': 'SAKHI GOPAL',
               'SINI': 'SINI JN',
               'SIOB': 'SAMAKHIALI B G',
               'SIP': 'SURAIMANPUR',
               'SIR': 'SIRHIND JN',
               'SJN': 'SANJAN',
               'SJP': 'SHUJALPUR',
               'SKB': 'SHIKOHABAD JN',
               'SKM': 'SINGARAYAKONDA',
               'SKP': 'SHANKARPALLI',
               'SKS': 'SALEKASA',
               'SKT': 'SAKTI',
               'SKZR': 'SIRPUR KAGAZNGR',
               'SLD': 'SAKALDIHA',
               'SLGR': 'SIMALUGURI JN',
               'SLI': 'SANGLI',
               'SLN': 'SULTANPUR',
               'SLO': 'SAMALKOT JN',
               'SLW': 'SOHWAL',
               'SMBJ': 'SHRI MAHABIRJI',
               'SMBX': 'SAMBA',
               'SMK': 'SAMALKHA',
               'SMT': 'SALAMATPUR',
               'SNI': 'SINDI',
               'SNP': 'SONIPAT',
               'SNT': 'SAINTHIA',
               'SOD': 'SOJAT ROAD',
               'SOG': 'SURATGARH JN',
               'SOH': 'SIROHI ROAD',
               'SPE': 'SULLURUPETA',
               'SPJ': 'SAMASTIPUR JN',
               'SPN': 'SHAHJEHANPUR',
               'SPRD': 'SINGAPURAM ROAD',
               'SPT': 'SOMPETA',
               'SPZ': 'SAMPLA',
               'SRC': 'SANTRAGACHI JN',
               'SRE': 'SAHARANPUR',
               'SRGM': 'SRIRANGAM',
               'SRID': 'SHRIDHAM',
               'SRJ': 'SHANKARGARH',
               'SRP': 'SERAMPORE',
               'SRR': 'SHORANUR JN',
               'SRT': 'SATUR',
               'SRTL': 'SHERTALAI',
               'SRU': 'SALEMPUR JN',
               'SSB': 'SHAKURBASTI',
               'SSM': 'SASARAM',
               'SSPN': 'SAI P NILAYAM',
               'ST': 'SURAT',
               'STA': 'SATNA',
               'STL': 'SIMULTALA',
               'STN': 'SITARAMPUR',
               'STR': 'SATARA',
               'STW': 'SAHATWAR',
               'SUNR': 'SURENDRANAGAR',
               'SUR': 'SOLAPUR JN',
               'SV': 'SIWAN JN',
               'SVA': 'SUWASRA',
               'SWM': 'SAWAI MADHOPUR',
               'SWPR': 'SEWAPURI',
               'SWR': 'SONUA',
               'SZM': 'SUBZI MANDI',
               'TA': 'TANUR',
               'TAN': 'TARANA ROAD',
               'TAR': 'THARSA',
               'TATA': 'TATANAGAR JN',
               'TAZ': 'TARGAON',
               'TBM': 'TAMBARAM',
               'TBN': 'TIMARNI',
               'TBT': 'TALBAHAT',
               'TBV': 'TIMBARVA',
               'TCR': 'THRISUR',
               'TDD': 'TADEPALLIGUDEM',
               'TDL': 'TUNDLA JN',
               'TDN': 'TIRUPARANKNDRM',
               'TDO': 'TANDA URMAR',
               'TDP': 'TODARPUR',
               'TDU': 'TANDUR',
               'TDV': 'THONDEBHAVI',
               'TEA': 'TAREGNA',
               'TEL': 'TENALI JN',
               'TEN': 'TIRUNELVELI',
               'TET': 'TETULMARI',
               'TGA': 'TEGHRA',
               'TGL': 'TUGGALI',
               'TGM': 'TANGARMUNDA',
               'TGN': 'TALEGAON',
               'TGQ': 'TENGANMADA',
               'THAN': 'THAN JN',
               'THB': 'THANA BIHPUR JN',
               'THDR': 'THANDLA RD',
               'THMR': 'THATHANA MITHRI',
               'THUR': 'THURIA',
               'THV': 'THERUBALI',
               'THVM': 'THIVIM',
               'THY': 'THADI',
               'TIG': 'TITLAGARH',
               'TIHU': 'TIHU',
               'TIM': 'TIMMANACHERLA',
               'TIR': 'TIRUR',
               'TIS': 'TATISILWAI',
               'TIT': 'TALIT',
               'TIU': 'TILARU',
               'TK': 'TUMKUR',
               'TKD': 'TUGLAKABAD',
               'TKLB': 'TAKLI BHANSALI',
               'TKN': 'TANKUPPA',
               'TKQ': 'TRIKARPUR',
               'TKR': 'TAKARI',
               'TKRI': 'TIKIRI',
               'TKWD': 'TIKEKARWADI',
               'TLD': 'TILDA',
               'TLH': 'TILHAR',
               'TLHD': 'TALCHER ROAD',
               'TLHR': 'TALCHER',
               'TLJ': 'TALJHARI',
               'TLT': 'TILATI',
               'TLU': 'TARLUPADU',
               'TLV': 'TALVADYA',
               'TLY': 'THALASSERY',
               'TMC': 'TALAMANCHI',
               'TMQ': 'TIRUMANGALAM',
               'TMR': 'TUMSAR ROAD',
               'TMV': 'TINDIVANAM',
               'TN': 'TUTICORIN',
               'TNA': 'THANE',
               'TNGL': 'TORANAGALLU',
               'TNKU': 'TANUKU',
               'TNR': 'TANGUTURU',
               'TORI': 'TORI',
               'TOU': 'TELAPROLU',
               'TP': 'TIRCHRPALI FORT',
               'TPH': 'TINPAHAR JN',
               'TPJ': 'TIRUCHCHIRAPALI',
               'TPQ': 'TOPOKAL',
               'TPT': 'TIRUPATTUR JN',
               'TPTY': 'TIRUPATI',
               'TPZ': 'TAPRI',
               'TRKR': 'TUREKALA ROAD',
               'TRL': 'TRIVELLORE',
               'TRO': 'TIRORA',
               'TRR': 'TARAORI',
               'TRT': 'TIRUTTANI',
               'TRTR': 'TRIUPUNITTURA',
               'TRVL': 'TIRUVALLA',
               'TSA': 'TISUA',
               'TSF': 'TAHSIL FATEHPUR',
               'TSK': 'TINSUKIA JN',
               'TSR': 'TSUNDURU',
               'TTR': 'TIPTUR',
               'TTU': 'TETTU',
               'TU': 'TADIPATRI',
               'TUN': 'TOHANA',
               'TUNI': 'TUNI',
               'TUP': 'TIRUPPUR',
               'TUVR': 'TURAVUR',
               'TUX': 'TUNIA',
               'TVC': 'TRIVANDRUM CNTL',
               'TVL': 'TADWAL',
               'TVP': 'TRIVANDRUM PETT',
               'TWG': 'TWINING GANJ',
               'TXD': 'TYADA',
               'UAA': 'UPPALA',
               'UAM': 'UDAGAMANDALAM',
               'UBC': 'AMBALA CITY',
               'UBL': 'HUBLI JN',
               'UBR': 'UMBARGAM ROAD',
               'UCA': 'UCHANA',
               'UCR': 'UNCHAHAR JN',
               'UD': 'UDUPI',
               'UDGR': 'UDGIR',
               'UDL': 'ANDAL JN',
               'UDM': 'UNDASA MADHAWPU',
               'UDN': 'UDHNA JN',
               'UDZ': 'UDAIPUR CITY',
               'UGD': 'UPPUGUNDURU',
               'UGNA': 'UGNA HALT',
               'UGR': 'UGAR KHURD',
               'UGWE': 'UGWE',
               'UHL': 'UNA HIMACHAL',
               'UHP': 'UDHAMPUR',
               'UHR': 'UNCHHERA',
               'UIH': 'UMARIA ISPA HLT',
               'UJ': 'UJALVAV',
               'UJA': 'UNJHA',
               'UJH': 'UJHANI',
               'UJN': 'UJJAIN JN',
               'UJP': 'UJIARPUR',
               'UKA': 'UKHRA',
               'UKD': 'ULINDAKONDA',
               'UKH': 'UKHALI',
               'UKL': 'UTTUKULI',
               'UKN': 'UKLANA',
               'UKR': 'UDALKACHAR',
               'ULA': 'UMRA NALA',
               'ULB': 'ULUBARIA',
               'ULD': 'ACHALDA',
               'ULG': 'UDALGURI'}
